### ISSUE TITLE
[QST] Failed to dlopen libcuda.so

### ISSUE THREAD

**Issue by Arkaikus** [rapidsai/cudf#10308]
Hi

I installed everything and got cuda working on my Ubuntu-20 wsl instance but for some reason trying to import cudf or cugraph gives me this output: `RuntimeError: Failed to dlopen libcuda.so`
``` bash
Python 3.8.12 | packaged by conda-forge | (default, Jan 30 2022, 23:42:07) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudf
Traceback (most recent call last):
  File "cuda/_cuda/ccuda.pyx", line 3553, in cuda._cuda.ccuda._cuInit
  File "cuda/_cuda/ccuda.pyx", line 424, in cuda._cuda.ccuda.cuPythonInit
RuntimeError: Failed to dlopen libcuda.so
Exception ignored in: 'cuda._lib.ccudart.utils.cudaPythonGlobal.lazyInit'
Traceback (most recent call last):
  File "cuda/_cuda/ccuda.pyx", line 3553, in cuda._cuda.ccuda._cuInit
  File "cuda/_cuda/ccuda.pyx", line 424, in cuda._cuda.ccuda.cuPythonInit
RuntimeError: Failed to dlopen libcuda.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sgiraldo/miniconda3/envs/rapids-22.02/lib/python3.8/site-packages/cudf/__init__.py", line 5, in <module>
    validate_setup()
  File "/home/sgiraldo/miniconda3/envs/rapids-22.02/lib/python3.8/site-packages/cudf/utils/gpu_utils.py", line 60, in validate_setup
    gpus_count = getDeviceCount()
  File "/home/sgiraldo/miniconda3/envs/rapids-22.02/lib/python3.8/site-packages/rmm/_cuda/gpu.py", line 99, in getDeviceCount
    status, count = cudart.cudaGetDeviceCount()
  File "cuda/cudart.pyx", line 8141, in cuda.cudart.cudaGetDeviceCount
  File "cuda/ccudart.pyx", line 486, in cuda.ccudart.cudaGetDeviceCount
  File "cuda/_lib/ccudart/ccudart.pyx", line 1463, in cuda._lib.ccudart.ccudart._cudaGetDeviceCount
  File "cuda/_cuda/ccuda.pyx", line 3583, in cuda._cuda.ccuda._cuDeviceGetCount
RuntimeError: Function "cuDeviceGetCount" not found
```
From nvidia side I got everything working, and `/usr/lib/wsl/lib` where the `so` files are located is in PATH, this is the output of `/usr/local/cuda-11.4/samples/1_Utilities/deviceQuery`

```
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "NVIDIA GeForce GTX 1050"
  CUDA Driver Version / Runtime Version          11.6 / 11.4
  CUDA Capability Major/Minor version number:    6.1
  Total amount of global memory:                 4096 MBytes (4294836224 bytes)
  (005) Multiprocessors, (128) CUDA Cores/MP:    640 CUDA Cores
  GPU Max Clock rate:                            1493 MHz (1.49 GHz)
  Memory Clock rate:                             3504 Mhz
  Memory Bus Width:                              128-bit
  L2 Cache Size:                                 524288 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total shared memory per multiprocessor:        98304 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Managed Memory:                Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      No
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 11.6, CUDA Runtime Version = 11.4, NumDevs = 1
Result = PASS
```
and nvidia-smi
```
Wed Feb 16 13:15:39 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.52       Driver Version: 511.79       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   47C    P8    N/A /  N/A |    412MiB /  4096MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

I followed the steps here https://docs.nvidia.com/cuda/wsl-user-guide/index.html

Best,

**Comment by gmarkall** [comment]
@Arkaikus Can you provide the output of `ldconfig -v` please?

**Comment by Arkaikus** [comment]
Sure, here [ldconfig.log](https://github.com/rapidsai/cudf/files/8083957/ldconfig.log)

**Comment by Arkaikus** [comment]
Somehow solved it with
- `nano ~/.bashrc`
- Add `export LD_LIBRARY_PATH="/usr/lib/wsl/lib/"`

No i'm having problems with reading from csv, related issue #9861

**Comment by gmarkall** [comment]
Many thanks for the info - I suspect there's another `libcuda.so` somehow installed somewhere in the system that did get found ahead of the one in `/usr/lib/wsl/lib`, which was resolved when you added it to the dynamic linker path. You might be able to find out where another `libcuda.so` is by running `locate libcuda.so` (if that's installed / set up) or by using `strace python -c "import cudf"` when you don't have the linker path set (feel free to share the output of either of these commands too).

**Comment by Arkaikus** [comment]
Hi got problems with locate but here is the output of strace 
[strace.log](https://github.com/rapidsai/cudf/files/8092679/strace.log)

i found another libcuda.so in /usr/local/cuda-11.4/targets/x86_64-linux/lib/stubs/
```bash
(rapids-22.02) sgiraldo@ARKAIKUS-PC:/usr/local/cuda-11.4/targets/x86_64-linux/lib/stubs$ ls
libcublas.so    libcufftw.so      libcusparse.so  libnppidei.so  libnppist.so  libnvidia-ml.so
libcublasLt.so  libcurand.so      libnppc.so      libnppif.so    libnppisu.so  libnvjpeg.so
libcuda.so      libcusolver.so    libnppial.so    libnppig.so    libnppitc.so  libnvrtc.so
libcufft.so     libcusolverMg.so  libnppicc.so    libnppim.so    libnpps.so
```

I set the LD_LIBRARY_PATH to that location but still got problems creating a dataframe

**Comment by taureandyernv** [comment]
@Arkaikus can you try using our Docker container?  It may be a potential work around while we work with you to solve this issue.

**Comment by Arkaikus** [comment]
> @Arkaikus can you try using our Docker container? It may be a potential work around while we work with you to solve this issue.

I'll try and let you know

**Comment by Arkaikus** [comment]
I'll also link this issue #9753

thanks @devavret

**Comment by Arkaikus** [comment]
After trying a lot of things, I cleaned up the wsl ubuntu instance (leaving only the windows defaults and bashrc defaults) and ran
```bash
conda create -n rapids-21.08 -c conda-forge -c rapidsai -c nvidia rapids=21.08 python=3.8 cudatoolkit=11.0 basemap
```
no apt install, no nvidia toolkit install, no .deb install

The docker solution with the last rapids "stable" version didn't work for me and ain't got the time to check every version

21.08 version worked for me creating and loading the dataframes but some things like pandas indexers didnt, maybe there are workarounds but i will deal with that later

Thanks everyone

**Comment by taureandyernv** [comment]
We believe we found the bug in cuda-python.  Thanks @rboissel.  Will update once fixed and tested.

Also, I'm finding that with the workaround, `read_csv` is still temperamental.

**Comment by JacksonWuxs** [comment]
Hi everyone, I face the same error under native Ubuntu OS.

OS: Ubuntu 20.04
Python: python3.8
CUDA: V11.6
Install by running: ` conda create -n rapids22 -c rapidsai -c nvidia -c conda-forge cuml=22.02 python=3.8 cudatoolkit=11.5` (it is automatically generated by the official website of rapid)

When I run: `from cuml.cluster import HDBSCAN`
It raise: 
```
Traceback (most recent call last):
  File "cuda/_cuda/ccuda.pyx", line 3553, in cuda._cuda.ccuda._cuInit
  File "cuda/_cuda/ccuda.pyx", line 424, in cuda._cuda.ccuda.cuPythonInit
RuntimeError: Failed to dlopen libcuda.so
Exception ignored in: 'cuda._lib.ccudart.utils.cudaPythonGlobal.lazyInit'
Traceback (most recent call last):
  File "cuda/_cuda/ccuda.pyx", line 3553, in cuda._cuda.ccuda._cuInit
  File "cuda/_cuda/ccuda.pyx", line 424, in cuda._cuda.ccuda.cuPythonInit
RuntimeError: Failed to dlopen libcuda.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/myid/xw54582/miniconda3/envs/rapids22/lib/python3.8/site-packages/cuml/__init__.py", line 17, in <module>
    from cuml.common.base import Base
  File "/home/myid/xw54582/miniconda3/envs/rapids22/lib/python3.8/site-packages/cuml/common/__init__.py", line 17, in <module>
    from cuml.common.array import CumlArray
  File "/home/myid/xw54582/miniconda3/envs/rapids22/lib/python3.8/site-packages/cuml/common/array.py", line 25, in <module>
    from cudf import DataFrame
  File "/home/myid/xw54582/miniconda3/envs/rapids22/lib/python3.8/site-packages/cudf/__init__.py", line 5, in <module>
    validate_setup()
  File "/home/myid/xw54582/miniconda3/envs/rapids22/lib/python3.8/site-packages/cudf/utils/gpu_utils.py", line 60, in validate_setup
    gpus_count = getDeviceCount()
  File "/home/myid/xw54582/miniconda3/envs/rapids22/lib/python3.8/site-packages/rmm/_cuda/gpu.py", line 99, in getDeviceCount
    status, count = cudart.cudaGetDeviceCount()
  File "cuda/cudart.pyx", line 8141, in cuda.cudart.cudaGetDeviceCount
  File "cuda/ccudart.pyx", line 486, in cuda.ccudart.cudaGetDeviceCount
  File "cuda/_lib/ccudart/ccudart.pyx", line 1463, in cuda._lib.ccudart.ccudart._cudaGetDeviceCount
  File "cuda/_cuda/ccuda.pyx", line 3583, in cuda._cuda.ccuda._cuDeviceGetCount
RuntimeError: Function "cuDeviceGetCount" not found
```
