### ISSUE TITLE
Cuda out of memory after deleting all items 

### ISSUE THREAD

**Issue by mina807** [rapidsai/cudf#11203]
Hello, I'm having a problem with running code with cuDF. 

The message I keep getting is : 

![image](https://user-images.githubusercontent.com/82156937/177475821-a1bf56fc-3af6-42c8-b373-fa3b9e970280.png)

Currently I'm using A100 with 40Gb. 
First, 17gb of cuda_g is uploaded to GPU and in one iteration, each chunk of cuda_p should be uploaded to the gpu and finish the job.

In order to make sure that the `del` and `torch.cuda.empty_cache()` works properly, I put cuda_g in the iteration and deleted after finishing the job.
Here is the iteration part.

```
import cudf as cd
import cupy as cp

for i in range(1000):
    gc.collect
    torch.cuda.empty_cache()
    
    start_time1 = time.time()
    print(i)
    cuda_g = torch.FloatTensor(g).cuda()

    p = torch.from_numpy(split_emb_p[i])
    cuda_p = torch.FloatTensor(p).cuda()
    
    with numba.cuda.defer_cleanup():
        tmp_sim = cd.DataFrame(cos_sim(cuda_g, cuda_p))
        del cuda_p
        del cuda_g
        torch.cuda.empty_cache()
        mem = torch.cuda.memory_allocated()
        print(mem)
        tmp_sim.columns = split_patent_id[i]
        tmp_sim.index = grant_id['id']
        
        for k in range(tmp_sim.shape[1]):
            pt = tmp_sim.iloc[:,k]
            sort_pt_index = cp.argsort(-1*pt)
            top_indx = sort_pt_index[0:10000]
            a = pt.iloc[top_indx].to_pandas()
            del pt
            del sort_pt_index
            del top_indx
            gc.collect  
            torch.cuda.empty_cache()
            mem = torch.cuda.memory_allocated()
            print(mem)
            
            tmp = pd.DataFrame()

            tmp['grant_id'] = a.index.values
            tmp['sim_score'] = a.values
            tmp['patent_id'] = tmp_sim.columns[k]
            
            if k == 0 : 
                final_result = tmp
            else:
                final_result = pd.concat([final_result,tmp],axis = 0)
        
        del tmp_sim
        del final_result
        gc.collect
        torch.cuda.empty_cache()
        mem = torch.cuda.memory_allocated()
        print(mem)
        
        end_time1 = time.time()

        print("One iteration time: {}, {}th split".format(end_time1-start_time1, i))

```
I checked it all returned 0 in print(mem) but after 1 iteration it keep showing the error message. Besides even though I tried with the smaller size of the `split_emb_p ` (smaller size of embedding) but after several round it shows the same message. 

How can I solve this problem？

Current version info - cuda/11.4 and rapids-22.06 (can't use the latest version because of installing issue : https://stackoverflow.com/questions/72855047/installing-rapids-for-cuda-support)

**Comment by shwina** [comment]
Hi @mina807 -- does replacing `gc.collect` with `gc.collect()` (invoking the function) help?

**Comment by mina807** [comment]
Wow now it works smoothly !! Thanks a lot!! 👍
