### ISSUE TITLE
cuda runtime api error

### ISSUE THREAD

**Issue by yosh3289** [rapidsai/cudf#13112]
Hello,
I recently installed cuda with WSL2 linux environment, but when I tried `import cudf`, it gives me `numba.cuda.cudadrv.runtime.CudaRuntimeAPIError: [35] Call to cudaRuntimeGetVersion results in cudaErrorUnknown.` 
Any help would be appreciated!
CUDA Version: 11.8
Driver Version: 522.30
python 3.10.10
cuda-python               11.8.1          py310h01a121a_2    conda-forge
cudatoolkit               11.8.0              h37601d7_11    conda-forge
cudf                      23.02.00        cuda_11_py310_g5ad4a85b9d_0    rapidsai
cupy                      11.6.0          py310h9216885_0    conda-forge

**Comment by bdice** [comment]
What GPU do you have? Can you post the output of `nvidia-smi`? WSL2 support requires a GPU with Compute Capability 7.0 or higher. For consumer cards, that means the RTX 2000 series or newer.

**Comment by yosh3289** [comment]
> Hi @yosh3289, thanks for your question.
> 
> What GPU do you have? Can you post the output of `nvidia-smi`? WSL2 support requires a GPU with Compute Capability 7.0 or higher. For consumer cards, that means the RTX 2000 series or newer.

Hello @bdice ,thanks for your reply!
I got the following result from `nvidia-smi`:
<img width="579" alt="nvidia-smi截图" src="https://user-images.githubusercontent.com/27570755/231189264-ae44f0cc-3137-46b2-8e9c-4d7725a8e65f.png">

**Comment by bdice** [comment]
Hi @yosh3289, sorry for the delay. I don't think I have enough information to identify the problem. Can you share more about the commands you used to install, the version of Numba you have, and whether you can run [Numba + CUDA examples](https://numba.readthedocs.io/en/stable/cuda/examples.html) outside of cudf?

**Comment by yosh3289** [comment]
> Hi @yosh3289, sorry for the delay. I don't think I have enough information to identify the problem. Can you share more about the commands you used to install, the version of Numba you have, and whether you can run [Numba + CUDA examples](https://numba.readthedocs.io/en/stable/cuda/examples.html) outside of cudf?

Hello @bdice , I've successfully resolved my problem with hints from numba issue [https://github.com/numba/numba/issues/6777](url). 
By adding `export NUMBA_CUDA_DRIVER="/usr/lib/wsl/lib/libcuda.so.1"` in .bashrc, numba can now detect my GPU and runtime error is gone.
Thanks for your time @bdice !!
