### ISSUE TITLE
[BUG] Errors converting tables from arrow to cuDF

### ISSUE THREAD

**Issue by pentschev** [rapidsai/cudf#13771]
**Describe the bug**
We've been investigating an issue with Dask's new P2P shuffle algorithm where arrow tables are [converted to cuDF in this line](https://github.com/rapidsai/cudf/blob/branch-23.08/python/cudf/cudf/core/frame.py#L1104), ultimately causing the following error:

```c++
*** MemoryError: std::bad_alloc: CUDA error at: /datasets/pentschev/miniconda3/envs/cudf-invalid-address-src-230726/include/rmm/mr/device/cuda_async_view_memory_resource.hpp:121: cudaErrorIllegalAddress an illegal memory access was encountered
```

The error above is irrecoverable from a CUDA perspective, if we attach a debugger and attempt to call any CUDA functions we get the same `cudaErrorIllegalAddress` for any subsequent calls.  We don't have a clear understanding as to what causes that, various attempts at understanding the real source were frustrated. The closest we've got to understand what is going on was by converting the data to another format (e.g., pandas) and back, which succeeds. All workers fail at the same time while executing the same line but on different chunks of data, also hinting at something going on with the input arrow data. Essentially, the following change allows the workflow to complete successfully:

<details><summary>Workaround patch</summary>

```python
diff --git a/python/cudf/cudf/core/frame.py b/python/cudf/cudf/core/frame.py
index dcf44344cd..0ce092dc53 100644
--- a/python/cudf/cudf/core/frame.py
+++ b/python/cudf/cudf/core/frame.py
@@ -1101,7 +1101,11 @@ class Frame(BinaryOperand, Scannable):
         cudf_non_category_frame = {
             name: col
             for name, col in zip(
-                data.column_names, libcudf.interop.from_arrow(data)
+                data.column_names,
+                cudf._lib.interop.from_arrow(
+                    pa.Table.from_pandas(data.to_pandas())
+                ),
+
             )
         }

```

</details>

That seems to point at some potential error when parsing the input data that is somehow fixed when converting to pandas and back. With that in mind, I attempted to store the data to disk to both ORC and parquet and see what would happen. With ORC, storing to disk and reading it back also completes successfully, just like pandas. However, with parquet data we get a different error:

```python
*** OverflowError: CUDF failure at: /datasets/pentschev/src/cudf-invalid-address/cudf/cpp/src/copying/concatenate.cu:421: Total number of concatenated chars exceeds the column size limit
```

I'm uncertain as to whether the `cudaErrorIllegalAddress` and `OverflowError` are related or not, but I would appreciate the input of someone knowledgeable of the `cudf._lib.interop.from_arrow()` internals.

**Steps/Code to reproduce bug**
Unfortunately an MRE for `cudaErrorIllegalAddress` is unavailable, we can only reproduce it in a complex and long workflow that takes ~90 minutes to fail on a DGX-2 running with 16 GPUs. For the `OverflowError` we have the following reproducer:

<details><summary>Reproducer</summary>

```python
import rmm

rmm.mr.set_current_device_resource(
    rmm.mr.CudaAsyncMemoryResource(
        initial_pool_size=int(10e9),
    )
)

import cudf._lib
import pyarrow as pa


data_parquet = pa.parquet.read_table("cudf_from_arrow.parquet")
cudf._lib.interop.from_arrow(data_parquet)
```

</details>

Data can be found in [this link](https://drive.google.com/file/d/1h8DxcmOK97KSy9D9zpnG7UB1R2NOWB8d/view?usp=sharing), as GH limits file size to 25MB and the full data is 500MB+ compressed.

<details><summary>Expected output</summary>

```
Traceback (most recent call last):
  File "/datasets/pentschev/src/cudf-invalid-address/cudf-from-arrow-from-parquet.py", line 14, in <module>
    cudf._lib.interop.from_arrow(data_parquet)
  File "/datasets/pentschev/miniconda3/envs/cudf-invalid-address-src-230726/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "interop.pyx", line 182, in cudf._lib.interop.from_arrow
OverflowError: CUDF failure at: /datasets/pentschev/src/cudf-invalid-address/cudf/cpp/src/copying/concatenate.cu:421: Total number of concatenated chars exceeds the column size limit
```

</details>

**Expected behavior**
The arrow to cuDF conversion should succeed without errors.

**Environment overview (please complete the following information)**
 - Environment location: bare-metal
 - Method of cuDF install: both conda and from source

**Environment details**
<details><summary>Click here to see environment details</summary><pre>

     **git***
     commit e0fa34b6953490dbf15576884cdd3fbbfac87b3c (HEAD -> branch-23.08, origin/branch-23.08, origin/HEAD)
     Author: Vukasin Milovanovic <vmilovanovic@nvidia.com>
     Date:   Fri Jul 21 13:10:38 2023 -0700

     Remove the erroneous "empty level" short-circuit from ORC reader (#13722)

     Closes #13709

     ORC reader skips some decode steps in the corner case where a column hierarchy level contains no data (e.g. struct with no validity mask).
     However, some of the skipped steps might still be required; for example, null masks need to the propagated to the child columns.

     This PR removes the short-circuit in the corner case, allowing correct decode when null masks need to be propagated.
     This PR also moves creation of the time zone table out of the level-by-level loop, as it can just be reused at all levels.

     Authors:
     - Vukasin Milovanovic (https://github.com/vuule)

     Approvers:
     - Bradley Dice (https://github.com/bdice)
     - Divye Gala (https://github.com/divyegala)

     URL: https://github.com/rapidsai/cudf/pull/13722
     **git submodules***

     ***OS Information***
     DGX_NAME="DGX Server"
     DGX_PRETTY_NAME="NVIDIA DGX Server"
     DGX_SWBUILD_DATE="2023-03-27-13-31-04"
     DGX_SWBUILD_VERSION="5.5.0"
     DGX_COMMIT_ID="b2e06e0"
     DGX_PLATFORM="DGX Server for DGX-2"
     DGX_SERIAL_NUMBER="0574318000281"
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=20.04
     DISTRIB_CODENAME=focal
     DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
     NAME="Ubuntu"
     VERSION="20.04.6 LTS (Focal Fossa)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 20.04.6 LTS"
     VERSION_ID="20.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=focal
     UBUNTU_CODENAME=focal
     Linux exp01 5.4.0-150-generic #167-Ubuntu SMP Mon May 15 17:35:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

     ***GPU Information***
     Wed Jul 26 13:16:10 2023
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  Tesla V100-SXM3...  Off  | 00000000:34:00.0 Off |                    0 |
     | N/A   34C    P0    50W / 350W |      0MiB / 32768MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla V100-SXM3...  Off  | 00000000:36:00.0 Off |                    0 |
     | N/A   32C    P0    50W / 350W |      0MiB / 32768MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   2  Tesla V100-SXM3...  Off  | 00000000:39:00.0 Off |                    0 |
     | N/A   40C    P0    51W / 350W |      0MiB / 32768MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   3  Tesla V100-SXM3...  Off  | 00000000:3B:00.0 Off |                    0 |
     | N/A   39C    P0    52W / 350W |      0MiB / 32768MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   4  Tesla V100-SXM3...  Off  | 00000000:57:00.0 Off |                    0 |
     | N/A   32C    P0    50W / 350W |      0MiB / 32768MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   5  Tesla V100-SXM3...  Off  | 00000000:59:00.0 Off |                    0 |
     | N/A   39C    P0    52W / 350W |      0MiB / 32768MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   6  Tesla V100-SXM3...  Off  | 00000000:5C:00.0 Off |                    0 |
     | N/A   33C    P0    51W / 350W |      0MiB / 32768MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   7  Tesla V100-SXM3...  Off  | 00000000:5E:00.0 Off |                    0 |
     | N/A   40C    P0    51W / 350W |      0MiB / 32768MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   8  Tesla V100-SXM3...  Off  | 00000000:B7:00.0 Off |                    0 |
     | N/A   32C    P0    51W / 350W |      0MiB / 32768MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   9  Tesla V100-SXM3...  Off  | 00000000:B9:00.0 Off |                    0 |
     | N/A   34C    P0    49W / 350W |      0MiB / 32768MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |  10  Tesla V100-SXM3...  Off  | 00000000:BC:00.0 Off |                    0 |
     | N/A   37C    P0    50W / 350W |      0MiB / 32768MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |  11  Tesla V100-SXM3...  Off  | 00000000:BE:00.0 Off |                    0 |
     | N/A   38C    P0    50W / 350W |      0MiB / 32768MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |  12  Tesla V100-SXM3...  Off  | 00000000:E0:00.0 Off |                    0 |
     | N/A   33C    P0    67W / 350W |      0MiB / 32768MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |  13  Tesla V100-SXM3...  Off  | 00000000:E2:00.0 Off |                    0 |
     | N/A   34C    P0    48W / 350W |      0MiB / 32768MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |  14  Tesla V100-SXM3...  Off  | 00000000:E5:00.0 Off |                    0 |
     | N/A   39C    P0    53W / 350W |      0MiB / 32768MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |  15  Tesla V100-SXM3...  Off  | 00000000:E7:00.0 Off |                    0 |
     | N/A   38C    P0    48W / 350W |      0MiB / 32768MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+

     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+
     WARNING: infoROM is corrupted at gpu 0000:39:00.0
     WARNING: infoROM is corrupted at gpu 0000:5C:00.0

     ***CPU***
     Architecture:                    x86_64
     CPU op-mode(s):                  32-bit, 64-bit
     Byte Order:                      Little Endian
     Address sizes:                   46 bits physical, 48 bits virtual
     CPU(s):                          96
     On-line CPU(s) list:             0-95
     Thread(s) per core:              2
     Core(s) per socket:              24
     Socket(s):                       2
     NUMA node(s):                    2
     Vendor ID:                       GenuineIntel
     CPU family:                      6
     Model:                           85
     Model name:                      Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz
     Stepping:                        4
     CPU MHz:                         3153.604
     CPU max MHz:                     3700.0000
     CPU min MHz:                     1200.0000
     BogoMIPS:                        5400.00
     Virtualization:                  VT-x
     L1d cache:                       1.5 MiB
     L1i cache:                       1.5 MiB
     L2 cache:                        48 MiB
     L3 cache:                        66 MiB
     NUMA node0 CPU(s):               0-23,48-71
     NUMA node1 CPU(s):               24-47,72-95
     Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
     Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
     Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
     Vulnerability Meltdown:          Mitigation; PTI
     Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
     Vulnerability Retbleed:          Mitigation; IBRS
     Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
     Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
     Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
     Vulnerability Srbds:             Not affected
     Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT vulnerable
     Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke md_clear flush_l1d arch_capabilities

     ***CMake***
     /datasets/pentschev/miniconda3/envs/cudf-invalid-address-src-230726/bin/cmake
     cmake version 3.26.4

     CMake suite maintained and supported by Kitware (kitware.com/cmake).

     ***g++***
     /datasets/pentschev/miniconda3/envs/cudf-invalid-address-src-230726/bin/g++
     g++ (conda-forge gcc 11.4.0-0) 11.4.0
     Copyright (C) 2021 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2022 NVIDIA Corporation
     Built on Wed_Sep_21_10:33:58_PDT_2022
     Cuda compilation tools, release 11.8, V11.8.89
     Build cuda_11.8.r11.8/compiler.31833905_0

     ***Python***
     /datasets/pentschev/miniconda3/envs/cudf-invalid-address-src-230726/bin/python
     Python 3.10.12

     ***Environment Variables***
     PATH                            : /home/nfs/pentschev/bin:/home/nfs/pentschev/.local/bin:/home/nfs/pentschev/nvim-linux64/bin:/usr/local/cuda/bin:/opt/bin:/home/nfs/pentschev/bin:/home/nfs/pentschev/.local/bin:/home/nfs/pentschev/nvim-linux64/bin:/datasets/pentschev/miniconda3/envs/cudf-invalid-address-src-230726/bin:/datasets/pentschev/miniconda3/condabin:/usr/local/cuda/bin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /datasets/pentschev/miniconda3/envs/cudf-invalid-address-src-230726
     PYTHON_PATH                     :

     ***conda packages***
     /datasets/pentschev/miniconda3/condabin/conda
     # packages in environment at /datasets/pentschev/miniconda3/envs/cudf-invalid-address-src-230726:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                  2_kmp_llvm    conda-forge
     _sysroot_linux-64_curr_repodata_hack 3                   h69a702a_13    conda-forge
     accessible-pygments       0.0.4              pyhd8ed1ab_0    conda-forge
     aiobotocore               2.5.0              pyhd8ed1ab_0    conda-forge
     aiohttp                   3.8.5           py310h2372a71_0    conda-forge
     aioitertools              0.11.0             pyhd8ed1ab_0    conda-forge
     aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
     alabaster                 0.7.13             pyhd8ed1ab_0    conda-forge
     anyio                     3.7.1              pyhd8ed1ab_0    conda-forge
     argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
     argon2-cffi-bindings      21.2.0          py310h5764c6d_3    conda-forge
     arrow                     1.2.3              pyhd8ed1ab_0    conda-forge
     asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
     async-lru                 2.0.3              pyhd8ed1ab_0    conda-forge
     async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
     attrs                     23.1.0             pyh71513ae_1    conda-forge
     autoconf                  2.71            pl5321h2b4cb7a_1    conda-forge
     automake                  1.16.5          pl5321ha770c72_0    conda-forge
     aws-c-auth                0.7.0                h435f46f_0    conda-forge
     aws-c-cal                 0.6.0                h93469e0_0    conda-forge
     aws-c-common              0.8.23               hd590300_0    conda-forge
     aws-c-compression         0.2.17               h862ab75_1    conda-forge
     aws-c-event-stream        0.3.1                h1e03375_0    conda-forge
     aws-c-http                0.7.10               h9ab9c9b_2    conda-forge
     aws-c-io                  0.13.27              h3870b5a_0    conda-forge
     aws-c-mqtt                0.8.13               hd4f18eb_5    conda-forge
     aws-c-s3                  0.3.12               he2a37c1_2    conda-forge
     aws-c-sdkutils            0.1.11               h862ab75_1    conda-forge
     aws-checksums             0.1.16               h862ab75_1    conda-forge
     aws-crt-cpp               0.20.2              h2a5cb19_18    conda-forge
     aws-sam-translator        1.71.0             pyhd8ed1ab_1    conda-forge
     aws-sdk-cpp               1.10.57             h7b9373a_16    conda-forge
     aws-xray-sdk              2.12.0             pyhd8ed1ab_0    conda-forge
     babel                     2.12.1             pyhd8ed1ab_1    conda-forge
     backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
     backports                 1.0                pyhd8ed1ab_3    conda-forge
     backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
     backports.zoneinfo        0.2.1           py310hff52083_7    conda-forge
     bat                       0.23.0               h0f5d50b_0    conda-forge
     bcrypt                    3.2.2           py310h5764c6d_1    conda-forge
     beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
     benchmark                 1.8.0                h59595ed_0    conda-forge
     binutils                  2.40                 hdd6e379_0    conda-forge
     binutils_impl_linux-64    2.40                 hf600244_0    conda-forge
     binutils_linux-64         2.40                 hbdbef99_1    conda-forge
     black                     22.3.0             pyhd8ed1ab_0    conda-forge
     blas                      1.0                         mkl    conda-forge
     bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
     blinker                   1.6.2              pyhd8ed1ab_0    conda-forge
     bokeh                     3.2.1              pyhd8ed1ab_0    conda-forge
     boto3                     1.26.76            pyhd8ed1ab_0    conda-forge
     botocore                  1.29.76            pyhd8ed1ab_0    conda-forge
     brotlipy                  0.7.0           py310h5764c6d_1005    conda-forge
     bzip2                     1.0.8                h7f98852_4    conda-forge
     c-ares                    1.19.1               hd590300_0    conda-forge
     c-compiler                1.5.2                h0b41bf4_0    conda-forge
     ca-certificates           2023.7.22            hbcca054_0    conda-forge
     cached-property           1.5.2                hd8ed1ab_1    conda-forge
     cached_property           1.5.2              pyha770c72_1    conda-forge
     cachetools                5.3.1              pyhd8ed1ab_0    conda-forge
     certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
     cffi                      1.15.1          py310h255011f_3    conda-forge
     cfgv                      3.3.1              pyhd8ed1ab_0    conda-forge
     cfn-lint                  0.77.10            pyhd8ed1ab_0    conda-forge
     charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
     click                     8.1.6           unix_pyh707e725_0    conda-forge
     cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
     cmake                     3.26.4               hcfe8598_0    conda-forge
     colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
     comm                      0.1.3              pyhd8ed1ab_0    conda-forge
     commonmark                0.9.1                      py_0    conda-forge
     contourpy                 1.1.0           py310hd41b1e2_0    conda-forge
     coverage                  7.2.7           py310h2372a71_0    conda-forge
     cryptography              41.0.2          py310h75e40e8_0    conda-forge
     cubinlinker               0.3.0           py310hfdf336d_0    rapidsai
     cuda-python               11.8.2          py310h01a121a_0    conda-forge
     cuda-sanitizer-api        11.8.86                       0    nvidia
     cuda-version              11.8                 h70ddcb2_2    conda-forge
     cudatoolkit               11.8.0              h37601d7_11    conda-forge
     cudf                      23.8.0                   pypi_0    pypi
     cupy                      12.1.0          py310h53f8385_0    conda-forge
     cxx-compiler              1.5.2                hf52228f_0    conda-forge
     cyrus-sasl                2.1.27               h54b06d7_7    conda-forge
     cython                    0.29.36         py310hc6cd4ac_0    conda-forge
     cytoolz                   0.12.2          py310h2372a71_0    conda-forge
     dask                      2023.7.0                 pypi_0    pypi
     dask-cuda                 23.08.00a       py310_230726_g8ff7af9_31    rapidsai-nightly
     dask-cudf                 23.8.0                   pypi_0    pypi
     dataclasses               0.8                pyhc8e2a94_3    conda-forge
     datasets                  1.18.3             pyhd8ed1ab_0    conda-forge
     debugpy                   1.6.7           py310heca2aa9_0    conda-forge
     decopatch                 1.4.10             pyhd8ed1ab_0    conda-forge
     decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
     defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
     dill                      0.3.7              pyhd8ed1ab_0    conda-forge
     distlib                   0.3.7              pyhd8ed1ab_0    conda-forge
     distributed               2023.6.0+56.gf48a8ca8          pypi_0    pypi
     distro                    1.8.0              pyhd8ed1ab_0    conda-forge
     dlpack                    0.5                  h9c3ff4c_0    conda-forge
     docker-py                 6.1.3              pyhd8ed1ab_0    conda-forge
     docutils                  0.19            py310hff52083_1    conda-forge
     doxygen                   1.8.20               had0d8f1_0    conda-forge
     ecdsa                     0.18.0             pyhd8ed1ab_1    conda-forge
     entrypoints               0.4                pyhd8ed1ab_0    conda-forge
     exceptiongroup            1.1.2              pyhd8ed1ab_0    conda-forge
     execnet                   2.0.2              pyhd8ed1ab_0    conda-forge
     executing                 1.2.0              pyhd8ed1ab_0    conda-forge
     expat                     2.5.0                hcb278e6_1    conda-forge
     fastavro                  1.8.0           py310h2372a71_0    conda-forge
     fastrlock                 0.8             py310hd8f1fbe_3    conda-forge
     filelock                  3.12.2             pyhd8ed1ab_0    conda-forge
     flake8                    3.8.3                      py_1    conda-forge
     flask                     2.3.2              pyhd8ed1ab_0    conda-forge
     flask_cors                3.0.10             pyhd3deb0d_0    conda-forge
     flit-core                 3.9.0              pyhd8ed1ab_0    conda-forge
     fmt                       9.1.0                h924138e_0    conda-forge
     fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
     freetype                  2.12.1               hca18f0e_1    conda-forge
     frozenlist                1.4.0           py310h2372a71_0    conda-forge
     fsspec                    2023.6.0           pyh1a96a4e_0    conda-forge
     future                    0.18.3             pyhd8ed1ab_0    conda-forge
     gcc                       11.4.0               h7baecda_1    conda-forge
     gcc_impl_linux-64         11.4.0               h7aa1c59_0    conda-forge
     gcc_linux-64              11.4.0               hfd045f2_1    conda-forge
     gdb                       12.1            py310hd73dadb_0    conda-forge
     gflags                    2.2.2             he1b5a44_1004    conda-forge
     glog                      0.6.0                h6f12383_0    conda-forge
     gmock                     1.13.0               ha770c72_1    conda-forge
     gmp                       6.2.1                h58526e2_0    conda-forge
     gmpy2                     2.1.2           py310h3ec546c_1    conda-forge
     graphql-core              3.2.3              pyhd8ed1ab_0    conda-forge
     greenlet                  2.0.2           py310hc6cd4ac_1    conda-forge
     gtest                     1.13.0               h00ab1b0_1    conda-forge
     gxx                       11.4.0               h7baecda_1    conda-forge
     gxx_impl_linux-64         11.4.0               h7aa1c59_0    conda-forge
     gxx_linux-64              11.4.0               hfc1ae95_1    conda-forge
     huggingface_hub           0.16.4             pyhd8ed1ab_0    conda-forge
     hypothesis                6.82.0             pyha770c72_0    conda-forge
     icu                       72.1                 hcb278e6_0    conda-forge
     identify                  2.5.26             pyhd8ed1ab_0    conda-forge
     idna                      3.4                pyhd8ed1ab_0    conda-forge
     imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
     importlib-metadata        6.8.0              pyha770c72_0    conda-forge
     importlib_metadata        6.8.0                hd8ed1ab_0    conda-forge
     importlib_resources       6.0.0              pyhd8ed1ab_1    conda-forge
     iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
     ipykernel                 6.25.0             pyh71e2992_0    conda-forge
     ipython                   8.14.0             pyh41d4057_0    conda-forge
     isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
     isort                     5.12.0             pyhd8ed1ab_1    conda-forge
     itsdangerous              2.1.2              pyhd8ed1ab_0    conda-forge
     jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
     jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
     jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
     joblib                    1.3.0              pyhd8ed1ab_1    conda-forge
     jschema-to-python         1.2.3              pyhd8ed1ab_0    conda-forge
     json5                     0.9.14             pyhd8ed1ab_0    conda-forge
     jsondiff                  2.0.0              pyhd8ed1ab_0    conda-forge
     jsonpatch                 1.32               pyhd8ed1ab_0    conda-forge
     jsonpickle                2.2.0              pyhd8ed1ab_0    conda-forge
     jsonpointer               2.0                        py_0    conda-forge
     jsonschema                4.18.4             pyhd8ed1ab_0    conda-forge
     jsonschema-specifications 2023.7.1           pyhd8ed1ab_0    conda-forge
     jsonschema-with-format-nongpl 4.18.4             pyhd8ed1ab_0    conda-forge
     junit-xml                 1.9                pyh9f0ad1d_0    conda-forge
     jupyter-cache             0.6.1              pyhd8ed1ab_0    conda-forge
     jupyter-lsp               2.2.0              pyhd8ed1ab_0    conda-forge
     jupyter_client            8.3.0              pyhd8ed1ab_0    conda-forge
     jupyter_core              5.3.1           py310hff52083_0    conda-forge
     jupyter_events            0.6.3              pyhd8ed1ab_1    conda-forge
     jupyter_server            2.7.0              pyhd8ed1ab_0    conda-forge
     jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
     jupyterlab                4.0.3              pyhd8ed1ab_0    conda-forge
     jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
     jupyterlab_server         2.24.0             pyhd8ed1ab_0    conda-forge
     kernel-headers_linux-64   3.10.0              h4a8ded7_13    conda-forge
     keyutils                  1.6.1                h166bdaf_0    conda-forge
     krb5                      1.21.1               h659d440_0    conda-forge
     lcms2                     2.15                 haa2dc70_1    conda-forge
     ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
     lerc                      4.0.0                h27087fc_0    conda-forge
     libabseil                 20230125.3      cxx17_h59595ed_0    conda-forge
     libarrow                  11.0.0          hc410076_26_cpu    conda-forge
     libblas                   3.9.0            16_linux64_mkl    conda-forge
     libbrotlicommon           1.0.9                h166bdaf_9    conda-forge
     libbrotlidec              1.0.9                h166bdaf_9    conda-forge
     libbrotlienc              1.0.9                h166bdaf_9    conda-forge
     libcblas                  3.9.0            16_linux64_mkl    conda-forge
     libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
     libcufile                 1.4.0.31                      0    nvidia
     libcufile-dev             1.4.0.31                      0    nvidia
     libcurand                 10.3.0.86                     0    nvidia
     libcurand-dev             10.3.0.86                     0    nvidia
     libcurl                   8.2.0                hca28451_0    conda-forge
     libdeflate                1.18                 h0b41bf4_0    conda-forge
     libedit                   3.1.20191231         he28a2e2_2    conda-forge
     libev                     4.33                 h516909a_1    conda-forge
     libevent                  2.1.12               hf998b51_1    conda-forge
     libexpat                  2.5.0                hcb278e6_1    conda-forge
     libffi                    3.4.2                h7f98852_5    conda-forge
     libgcc-devel_linux-64     11.4.0               h922705a_0    conda-forge
     libgcc-ng                 13.1.0               he5830b7_0    conda-forge
     libgfortran-ng            13.1.0               h69a702a_0    conda-forge
     libgfortran5              13.1.0               h15d22d2_0    conda-forge
     libgomp                   13.1.0               he5830b7_0    conda-forge
     libgoogle-cloud           2.12.0               hac9eb74_1    conda-forge
     libgrpc                   1.54.2               hb20ce57_2    conda-forge
     libhwloc                  2.9.1           nocuda_h7313eea_6    conda-forge
     libiconv                  1.17                 h166bdaf_0    conda-forge
     libjpeg-turbo             2.1.5.1              h0b41bf4_0    conda-forge
     libkvikio                 23.08.00a       cuda11_230726_gc45b5c4_29    rapidsai-nightly
     liblapack                 3.9.0            16_linux64_mkl    conda-forge
     libllvm14                 14.0.6               hcd5def8_3    conda-forge
     libnghttp2                1.52.0               h61bc06f_0    conda-forge
     libnsl                    2.0.0                h7f98852_0    conda-forge
     libntlm                   1.4               h7f98852_1002    conda-forge
     libnuma                   2.0.16               h0b41bf4_1    conda-forge
     libpng                    1.6.39               h753d276_0    conda-forge
     libprotobuf               3.21.12              h3eb15da_0    conda-forge
     librdkafka                1.9.2                ha5a0de0_2    conda-forge
     librmm                    23.08.00a       cuda11_230726_gb2ed023b_26    rapidsai-nightly
     libsanitizer              11.4.0               h4dcbe23_0    conda-forge
     libsodium                 1.0.18               h36c2ea0_1    conda-forge
     libsqlite                 3.42.0               h2797004_0    conda-forge
     libssh2                   1.11.0               h0841786_0    conda-forge
     libstdcxx-devel_linux-64  11.4.0               h922705a_0    conda-forge
     libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
     libthrift                 0.18.1               h8fd135c_2    conda-forge
     libtiff                   4.5.1                h8b53f26_0    conda-forge
     libtool                   2.4.7                h27087fc_0    conda-forge
     libunwind                 1.6.2                h9c3ff4c_0    conda-forge
     libutf8proc               2.8.0                h166bdaf_0    conda-forge
     libuuid                   2.38.1               h0b41bf4_0    conda-forge
     libuv                     1.44.2               hd590300_1    conda-forge
     libwebp-base              1.3.1                hd590300_0    conda-forge
     libxcb                    1.15                 h0b41bf4_0    conda-forge
     libxml2                   2.11.4               h0d562d8_0    conda-forge
     libzlib                   1.2.13               hd590300_5    conda-forge
     livereload                2.6.3              pyh9f0ad1d_0    conda-forge
     llvm-openmp               16.0.6               h4dfa4b3_0    conda-forge
     llvmlite                  0.40.1          py310h1b8f574_0    conda-forge
     locket                    1.0.0              pyhd8ed1ab_0    conda-forge
     lz4                       4.3.2           py310h0cfdcf0_0    conda-forge
     lz4-c                     1.9.4                hcb278e6_0    conda-forge
     m4                        1.4.18            h516909a_1001    conda-forge
     makefun                   1.15.1             pyhd8ed1ab_0    conda-forge
     markdown                  3.4.4              pyhd8ed1ab_0    conda-forge
     markdown-it-py            2.2.0              pyhd8ed1ab_0    conda-forge
     markupsafe                2.1.3           py310h2372a71_0    conda-forge
     matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
     mccabe                    0.6.1                      py_1    conda-forge
     mdit-py-plugins           0.4.0              pyhd8ed1ab_0    conda-forge
     mdurl                     0.1.0              pyhd8ed1ab_0    conda-forge
     mimesis                   10.1.0             pyhd8ed1ab_0    conda-forge
     mistune                   3.0.0              pyhd8ed1ab_0    conda-forge
     mkl                       2022.2.1         h84fe81f_16997    conda-forge
     moto                      4.1.13             pyhd8ed1ab_0    conda-forge
     mpc                       1.3.1                hfe3b2da_0    conda-forge
     mpfr                      4.2.0                hb012696_0    conda-forge
     mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
     msgpack-python            1.0.5           py310hdf3cbec_0    conda-forge
     multidict                 6.0.4           py310h1fa729e_0    conda-forge
     multiprocess              0.70.15         py310h2372a71_0    conda-forge
     mypy_extensions           1.0.0              pyha770c72_0    conda-forge
     myst-nb                   0.17.2             pyhd8ed1ab_0    conda-forge
     myst-parser               0.18.1             pyhd8ed1ab_0    conda-forge
     nbclient                  0.7.4              pyhd8ed1ab_0    conda-forge
     nbconvert                 7.7.3              pyhd8ed1ab_0    conda-forge
     nbconvert-core            7.7.3              pyhd8ed1ab_0    conda-forge
     nbconvert-pandoc          7.7.3              pyhd8ed1ab_0    conda-forge
     nbformat                  5.9.1              pyhd8ed1ab_0    conda-forge
     nbsphinx                  0.9.2              pyhd8ed1ab_0    conda-forge
     ncurses                   6.4                  hcb278e6_0    conda-forge
     nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
     networkx                  2.8.8              pyhd8ed1ab_0    conda-forge
     ninja                     1.11.1               h924138e_0    conda-forge
     nodeenv                   1.8.0              pyhd8ed1ab_0    conda-forge
     notebook                  7.0.0              pyhd8ed1ab_0    conda-forge
     notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
     numba                     0.57.1          py310h0f6aa51_0    conda-forge
     numpy                     1.24.4          py310ha4c1d20_0    conda-forge
     numpydoc                  1.5.0              pyhd8ed1ab_0    conda-forge
     nvcc_linux-64             11.8                h41dc85b_22    conda-forge
     nvcomp                    2.6.1                h0800d71_2    conda-forge
     nvtx                      0.2.5           py310h1fa729e_0    conda-forge
     openapi-schema-validator  0.2.3              pyhd8ed1ab_0    conda-forge
     openapi-spec-validator    0.4.0              pyhd8ed1ab_1    conda-forge
     openjpeg                  2.5.0                hfec8fc6_2    conda-forge
     openssl                   3.1.1                hd590300_1    conda-forge
     orc                       1.8.4                h2f23424_0    conda-forge
     overrides                 7.3.1              pyhd8ed1ab_0    conda-forge
     packaging                 23.1               pyhd8ed1ab_0    conda-forge
     pandas                    1.5.3           py310h9b08913_1    conda-forge
     pandoc                    3.1.3                h32600fe_0    conda-forge
     pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
     paramiko                  3.2.0              pyhd8ed1ab_0    conda-forge
     parso                     0.8.3              pyhd8ed1ab_0    conda-forge
     partd                     1.4.0              pyhd8ed1ab_0    conda-forge
     pathspec                  0.11.1             pyhd8ed1ab_0    conda-forge
     pbr                       5.11.1             pyhd8ed1ab_0    conda-forge
     perl                      5.32.1          4_hd590300_perl5    conda-forge
     pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
     pickleshare               0.7.5                   py_1003    conda-forge
     pillow                    10.0.0          py310h582fbeb_0    conda-forge
     pip                       23.2.1             pyhd8ed1ab_0    conda-forge
     pkg-config                0.29.2            h36c2ea0_1008    conda-forge
     pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
     platformdirs              3.9.1              pyhd8ed1ab_0    conda-forge
     pluggy                    1.2.0              pyhd8ed1ab_0    conda-forge
     pooch                     1.7.0              pyha770c72_3    conda-forge
     pre-commit                3.3.3              pyha770c72_0    conda-forge
     prometheus_client         0.17.1             pyhd8ed1ab_0    conda-forge
     prompt-toolkit            3.0.39             pyha770c72_0    conda-forge
     prompt_toolkit            3.0.39               hd8ed1ab_0    conda-forge
     protobuf                  4.21.12         py310heca2aa9_0    conda-forge
     psutil                    5.9.5           py310h1fa729e_0    conda-forge
     pthread-stubs             0.4               h36c2ea0_1001    conda-forge
     ptxcompiler               0.8.1           py310h01a121a_0    conda-forge
     ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
     pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
     py-cpuinfo                9.0.0              pyhd8ed1ab_0    conda-forge
     py-spy                    0.3.14               h87a5ac0_0    conda-forge
     pyarrow                   11.0.0          py310he6bfd7f_26_cpu    conda-forge
     pyasn1                    0.4.8                      py_0    conda-forge
     pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
     pycparser                 2.21               pyhd8ed1ab_0    conda-forge
     pydantic                  1.10.11         py310h2372a71_0    conda-forge
     pydata-sphinx-theme       0.13.3             pyhd8ed1ab_0    conda-forge
     pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
     pygments                  2.15.1             pyhd8ed1ab_0    conda-forge
     pynacl                    1.5.0           py310h5764c6d_2    conda-forge
     pynvml                    11.4.1             pyhd8ed1ab_0    conda-forge
     pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
     pyorc                     0.8.0           py310h54605fe_5    conda-forge
     pyparsing                 3.1.0              pyhd8ed1ab_0    conda-forge
     pysocks                   1.7.1              pyha2e5f31_6    conda-forge
     pytest                    7.4.0              pyhd8ed1ab_0    conda-forge
     pytest-asyncio            0.21.1             pyhd8ed1ab_0    conda-forge
     pytest-benchmark          4.0.0              pyhd8ed1ab_0    conda-forge
     pytest-cases              3.6.14             pyhd8ed1ab_0    conda-forge
     pytest-cov                4.1.0              pyhd8ed1ab_0    conda-forge
     pytest-faulthandler       2.0.1                      py_0    conda-forge
     pytest-repeat             0.9.1              pyhd8ed1ab_0    conda-forge
     pytest-rerunfailures      12.0               pyhd8ed1ab_0    conda-forge
     pytest-timeout            2.1.0              pyhd8ed1ab_0    conda-forge
     pytest-xdist              3.3.1              pyhd8ed1ab_0    conda-forge
     python                    3.10.12         hd12c33a_0_cpython    conda-forge
     python-confluent-kafka    1.9.2           py310h5764c6d_2    conda-forge
     python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
     python-fastjsonschema     2.18.0             pyhd8ed1ab_0    conda-forge
     python-jose               3.3.0              pyh6c4a22f_1    conda-forge
     python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
     python-snappy             0.6.1           py310hcee4d7c_0    conda-forge
     python-xxhash             3.2.0           py310h1fa729e_0    conda-forge
     python_abi                3.10                    3_cp310    conda-forge
     pytorch                   1.11.0             py3.10_cpu_0    pytorch
     pytorch-mutex             1.0                         cpu    pytorch
     pytz                      2023.3             pyhd8ed1ab_0    conda-forge
     pywin32-on-windows        0.1.0              pyh1179c8e_3    conda-forge
     pyyaml                    6.0             py310h5764c6d_5    conda-forge
     pyzmq                     25.1.0          py310h5bbb5d0_0    conda-forge
     rapids-deduplication      0.1.0                    pypi_0    pypi
     rdma-core                 28.9                 h59595ed_1    conda-forge
     re2                       2023.03.02           h8c504da_0    conda-forge
     readline                  8.2                  h8228510_1    conda-forge
     recommonmark              0.7.1              pyhd8ed1ab_0    conda-forge
     referencing               0.30.0             pyhd8ed1ab_0    conda-forge
     regex                     2023.6.3        py310h2372a71_0    conda-forge
     remote-pdb                2.1.0                    pypi_0    pypi
     requests                  2.31.0             pyhd8ed1ab_0    conda-forge
     responses                 0.23.2             pyhd8ed1ab_0    conda-forge
     rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
     rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
     rhash                     1.4.3                hd590300_1    conda-forge
     rmm                       23.08.00a       cuda11_py310_230726_gb2ed023b_26    rapidsai-nightly
     rpds-py                   0.9.2           py310hcb5633a_0    conda-forge
     rsa                       4.9                pyhd8ed1ab_0    conda-forge
     s2n                       1.3.46               h06160fa_0    conda-forge
     s3fs                      2023.6.0           pyhd8ed1ab_0    conda-forge
     s3transfer                0.6.1              pyhd8ed1ab_0    conda-forge
     sacremoses                0.0.53             pyhd8ed1ab_0    conda-forge
     sarif-om                  1.0.4              pyhd8ed1ab_0    conda-forge
     scikit-build              0.17.6             pyh4af843d_0    conda-forge
     scipy                     1.11.1          py310ha4c1d20_0    conda-forge
     sed                       4.8                  he412f7d_0    conda-forge
     send2trash                1.8.2              pyh41d4057_0    conda-forge
     setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
     shellcheck                0.9.0                ha770c72_0    conda-forge
     six                       1.16.0             pyh6c4a22f_0    conda-forge
     snappy                    1.1.10               h9fff704_0    conda-forge
     sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
     snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
     sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
     soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
     spdlog                    1.11.0               h9b3ece8_1    conda-forge
     sphinx                    5.3.0              pyhd8ed1ab_0    conda-forge
     sphinx-autobuild          2021.3.14          pyhd8ed1ab_0    conda-forge
     sphinx-copybutton         0.5.2              pyhd8ed1ab_0    conda-forge
     sphinx-markdown-tables    0.0.17             pyh6c4a22f_0    conda-forge
     sphinxcontrib-applehelp   1.0.4              pyhd8ed1ab_0    conda-forge
     sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
     sphinxcontrib-htmlhelp    2.0.1              pyhd8ed1ab_0    conda-forge
     sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
     sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
     sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
     sphinxcontrib-websupport  1.2.4              pyhd8ed1ab_1    conda-forge
     sqlalchemy                2.0.19          py310h2372a71_0    conda-forge
     sshpubkeys                3.3.1              pyhd8ed1ab_0    conda-forge
     stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
     streamz                   0.6.4              pyh6c4a22f_0    conda-forge
     sympy                     1.12            pypyh9d50eac_103    conda-forge
     sysroot_linux-64          2.17                h4a8ded7_13    conda-forge
     tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
     tbb                       2021.9.0             hf52228f_0    conda-forge
     tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
     terminado                 0.17.1             pyh41d4057_0    conda-forge
     tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
     tk                        8.6.12               h27826a3_0    conda-forge
     tokenizers                0.13.1          py310h633acb5_2    conda-forge
     toml                      0.10.2             pyhd8ed1ab_0    conda-forge
     tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
     toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
     tornado                   6.3.2           py310h2372a71_0    conda-forge
     tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
     traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
     transformers              4.24.0             pyhd8ed1ab_0    conda-forge
     typed-ast                 1.5.5           py310h2372a71_0    conda-forge
     types-pyyaml              6.0.12.11          pyhd8ed1ab_0    conda-forge
     typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
     typing_extensions         4.7.1              pyha770c72_0    conda-forge
     typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
     tzdata                    2023c                h71feb2d_0    conda-forge
     ucx                       1.14.1               h4a2ce2d_2    conda-forge
     ucx-py                    0.33.00a        py310_230724_g8eef032_17    rapidsai-nightly
     ukkonen                   1.0.1           py310hbf28c38_3    conda-forge
     uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
     urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
     virtualenv                20.24.2            pyhd8ed1ab_0    conda-forge
     wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
     webcolors                 1.13               pyhd8ed1ab_0    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     websocket-client          1.6.1              pyhd8ed1ab_0    conda-forge
     werkzeug                  2.3.6              pyhd8ed1ab_0    conda-forge
     wheel                     0.41.0             pyhd8ed1ab_0    conda-forge
     wrapt                     1.15.0          py310h1fa729e_0    conda-forge
     xmltodict                 0.13.0             pyhd8ed1ab_0    conda-forge
     xorg-libxau               1.0.11               hd590300_0    conda-forge
     xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
     xxhash                    0.8.1                h0b41bf4_0    conda-forge
     xyzservices               2023.7.0           pyhd8ed1ab_0    conda-forge
     xz                        5.2.6                h166bdaf_0    conda-forge
     yaml                      0.2.5                h7f98852_2    conda-forge
     yarl                      1.9.2           py310h2372a71_0    conda-forge
     zeromq                    4.3.4                h9c3ff4c_1    conda-forge
     zict                      3.0.0              pyhd8ed1ab_0    conda-forge
     zipp                      3.16.2             pyhd8ed1ab_0    conda-forge
     zlib                      1.2.13               hd590300_5    conda-forge
     zstd                      1.5.2                hfc55251_7    conda-forge

</pre></details>

**Comment by pentschev** [comment]
cc @quasiben @charlesbluca

**Comment by rjzamora** [comment]
Thank you for writing this up @pentschev. For your reproducer, do you still get an overflow error if you convert `data_parquet` to pandas, and then to cudf?

**Comment by pentschev** [comment]
Yes, that still happens. I tried pyarrow->pandas->cuDF and pyarrow->pandas->pyarrow->cuDF and both raise the same `OverflowError`. In this case it seems that the data itself may be bad now, which didn't happen when converting to ORC instead of parquet. Could this be a parquet limitation instead?

**Comment by GregoryKimball** [comment]
Thank you @pentschev for sharing your investigation. Would you please help me understand the scope a bit better?

* For the P2P shuffle error, do you think we should add your workaround patch in `frame.py` to cuDF? Perhaps it would be good to get feedback from @shwina or @galipremsagar on this idea.
* For the Parquet read error on roundtripping - do you think that is a separate issue? or do you think the Parquet write call was made with an invalid table?
* Would you please help me understand the connection to `cudf._lib.interop.from_arrow()`? Are you sure the incoming data from Dask was valid?

**Comment by pentschev** [comment]
> * For the P2P shuffle error, do you think we should add your workaround patch in `frame.py` to cuDF? 

No, that was solely for experimenting purposes. There should be no need to convert from arrow to pandas and back, AFAIK it seems to succeed elsewhere as nobody reported similar issues, the P2P shuffle is the only place I see this happening.

> * For the Parquet read error on roundtripping - do you think that is a separate issue? or do you think the Parquet write call was made with an invalid table?

I don't know. My intent was to dump the same data that eventually leads to the `cudaErrorIllegalAddress` in the P2P shuffle workflow and create a minimal reproducer. The same `cudaErrorIllegalAddress` doesn't reproduce though and we instead get the `OverflowError`. I'm hoping that this data may hint at a specific problem with data itself or cuDF's implementation that could help clarify why it all happens.

> * Would you please help me understand the connection to `cudf._lib.interop.from_arrow()`? Are you sure the incoming data from Dask was valid?

This is where things are fuzzy, it's possible something is corrupting data but in that case we would want cuDF to tell us about it and not eventually lead the program to a `cudaErrorIllegalAddress`. The fact that we can convert the arrow table to pandas and back and that then cuDF can read it successfully seems to point at pandas either doing something right where cuDF isn't, or maybe even "healing" that data. In any case it seems plausible that something within the confines of `cudf._lib.interop.from_arrow()` eventually causes `cudaErrorIllegalAddress` where it should not, but I couldn't tell where it happens as the error is only raised when the stream/device synchronizes, as expected when such CUDA errors occur.

**Comment by GregoryKimball** [comment]
Thank you @pentschev for answering my questions. I took a look at the data and repro. This appears to be document data for LLM training - and a lot of it per file! We recommend only processing 100K or fewer documents per dataframe partition. This dataset has ~500K documents in it. 
```
df = cudf.read_parquet('cudf_from_arrow.parquet')
...
OverflowError: CUDF failure at: /opt/conda/conda-bld/work/cpp/include/cudf/detail/sizes_to_offsets_iterator.cuh:320: Size of output exceeds the column size limit
```

As far as the overflow error, this is expected behavior. We only support up to 2.1 billion characters in a strings column. Please see https://github.com/rapidsai/cudf/issues/13733 for our design work to raise the character limit.  I suspect that both the `OverflowError` and the `cudaErrorIllegalAddress` error will go away if you use finer partitions.

**Comment by pentschev** [comment]
While the limit you're talking about above makes sense from a current implementation perspective, certainly `cudaErrorIllegalAddress` should never happen. If this is a limitation, it should be accounted for and a proper error should be thrown instead. Fortunately, I was able to generate a proper data dump that allows reproducing the error, the only thing different is that this time I dumped using the feather format, where dumping the same data to different formats behave differently (IIRC, parquet will raise an `OverflowError` and ORC will succeed).

With the MRE I was then able to run `from_arrow()` with `compute-sanitizer` which pointed to an out-of-bounds read error in [`fused_concatenate_string_chars_kernel`](https://github.com/rapidsai/cudf/blob/da6ac73e8849a6d5d7471f8aad60a8fd1141fe22/cpp/src/strings/copying/concatenate.cu#L172-L200). The fix for that was pretty simple as it is merely the same as of https://github.com/rapidsai/cudf/pull/10344. What is frustrating here is that we spent dozens of engineering hours on this problem and it could have been prevented should there be a follow-up to the question in https://github.com/rapidsai/cudf/issues/10333#issuecomment-1048229610 .

In any case, I've now put up a fix for the `cudaErrorIllegalAddress` in https://github.com/rapidsai/cudf/pull/13838. I confirmed it resolves that problem, but I spent some time (far too much) on it and failed to come up with the appropriate test. If I'm understanding the codeflow correctly, to hit reach that kernel in a way to make it fail we need data that makes the [`use_fused_kernel_heuristic`](https://github.com/rapidsai/cudf/blob/da6ac73e8849a6d5d7471f8aad60a8fd1141fe22/cpp/src/strings/copying/concatenate.cu#L48-L54) evaluate to `true` and the `total_bytes` must be large enough to require a 64-bit integer for addressing. In my mind, the appropriate test would have a large enough number of columns (failing data has `5000`) and the `total_bytes` must also be large (failing data is `1431647652` bytes long). I would appreciate if someone could help me creating some synthetic test data that we could use to test the kernel actually succeeds.

**Comment by GregoryKimball** [comment]
Thank you @pentschev for investing time in this, and please excuse me for not recognizing the severity of this issue earlier. Previously when this kernel overflow issue was discovered, we opened #10368 to track other offending kernels. It looks like this issue missed the kernels mentioned in (#10333 (comment))[https://github.com/rapidsai/cudf/issues/10333#issuecomment-1048229610]. I updated this issue and we will reopen the investigation. The Spark-RAPIDS team also has interest in preventing this kind of kernel error.
