### ISSUE TITLE
[BUG] OSError: libcudart.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by qsimeon** [rapidsai/cudf#14530]
I pip installed in my conda environment (the conda installation didn't work) using `pip install cudf-cu11 --extra-index-url=https://pypi.nvidia.com`. Then I ran a cell in a Jupyter notebook opened with my conda environment (`worm-graph`) active that contained just this line:
```
%load_ext cudf.panda
```
and it threw this error.

```
{
	"name": "OSError",
	"message": "libcudart.so: cannot open shared object file: No such file or directory",
	"stack": "---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[3], line 1
----> 1 import cudf.pandas
      2 # cudf.pandas.install()

File /om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.9/site-packages/cudf/__init__.py:10
      7 from cudf.utils.gpu_utils import validate_setup
      9 _setup_numba()
---> 10 validate_setup()
     12 import cupy
     13 from numba import config as numba_config, cuda

File /om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.9/site-packages/cudf/utils/gpu_utils.py:95, in validate_setup()
     85     minor_version = getDeviceAttribute(
     86         cudaDeviceAttr.cudaDevAttrComputeCapabilityMinor, 0
     87     )
     88     warnings.warn(
     89         \"A GPU with NVIDIA Pascal™ (Compute Capability 6.0) \"
     90         \"or newer architecture is required.\
\"
     91         f\"Detected GPU 0: {device_name}\
\"
     92         f\"Detected Compute Capability: {major_version}.{minor_version}\"
     93     )
---> 95 cuda_runtime_version = runtimeGetVersion()
     97 if cuda_runtime_version < 11000:
     98     # Require CUDA Runtime version 11.0 or greater.
     99     major_version = cuda_runtime_version // 1000

File /om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.9/site-packages/rmm/_cuda/gpu.py:88, in runtimeGetVersion()
     84 # TODO: Replace this with `cuda.cudart.cudaRuntimeGetVersion()` when the
     85 # limitation is fixed.
     86 import numba.cuda
---> 88 major, minor = numba.cuda.runtime.get_version()
     89 return major * 1000 + minor * 10

File /om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.9/site-packages/numba/cuda/cudadrv/runtime.py:111, in Runtime.get_version(self)
    107 \"\"\"
    108 Returns the CUDA Runtime version as a tuple (major, minor).
    109 \"\"\"
    110 rtver = ctypes.c_int()
--> 111 self.cudaRuntimeGetVersion(ctypes.byref(rtver))
    112 # The version is encoded as (1000 * major) + (10 * minor)
    113 major = rtver.value // 1000

File /om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.9/site-packages/numba/cuda/cudadrv/runtime.py:65, in Runtime.__getattr__(self, fname)
     62 argtypes = proto[1:]
     64 if not self.is_initialized:
---> 65     self._initialize()
     67 # Find function in runtime library
     68 libfn = self._find_api(fname)

File /om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.9/site-packages/numba/cuda/cudadrv/runtime.py:51, in Runtime._initialize(self)
     47     msg = (\"CUDA is disabled due to setting NUMBA_DISABLE_CUDA=1 \"
     48            \"in the environment, or because CUDA is unsupported on \"
     49            \"32-bit systems.\")
     50     raise CudaSupportError(msg)
---> 51 self.lib = open_cudalib('cudart')
     53 self.is_initialized = True

File /om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.9/site-packages/numba/cuda/cudadrv/libs.py:64, in open_cudalib(lib)
     62 def open_cudalib(lib):
     63     path = get_cudalib(lib)
---> 64     return ctypes.CDLL(path)

File /om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.9/ctypes/__init__.py:374, in CDLL.__init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    371 self._FuncPtr = _FuncPtr
    373 if handle is None:
--> 374     self._handle = _dlopen(self._name, mode)
    375 else:
    376     self._handle = handle

OSError: libcudart.so: cannot open shared object file: No such file or directory"
}
```

**Comment by bdice** [comment]
Hi @qsimeon, how did you install the CUDA Toolkit? You need CUDA 11 installed on your system in order to use `-cu11` pip packages, or CUDA 12 to use `-cu12` pip packages.

The conda packages of RAPIDS will handle the CUDA Toolkit requirements for you, so long as you have a CUDA driver installed on your system. If you can install with conda, it may be a better option.

If you're still having trouble, please share more about how you set up CUDA and the output of `nvidia-smi`.

**Comment by qsimeon** [comment]
@bdice thanks. Currently attempting to install with conda now using `conda install --solver=libmamba --force-reinstall -n worm-graph -c rapidsai -c conda-forge -c nvidia rapids=23.10 python=3.9 cuda-version=11.8`
Seems to be making progress. Will close issue if everything installs successfully.

**Comment by qsimeon** [comment]
Got through to the end of installing with the conda command above. But running `%load_ext cudf.pandas` or `import cudf.pandas; cudf.pandas.install()` in a Jupyter notebook both throw this new error:
```
{
	"name": "ImportError",
	"message": "/om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.9/site-packages/cudf/_lib/../../../../libcudf.so: undefined symbol: _ZN5arrow2fs17FileSystemFromUriERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPS6_",
	"stack": "---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[13], line 1
----> 1 get_ipython().run_line_magic('load_ext', 'cudf.pandas  # pandas operations now use the GPU!')
      2 # import pandas as pd

File /om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.9/site-packages/IPython/core/interactiveshell.py:2454, in InteractiveShell.run_line_magic(self, magic_name, line, _stack_depth)
   2452     kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2453 with self.builtin_trap:
-> 2454     result = fn(*args, **kwargs)
   2456 # The code below prevents the output from being displayed
   2457 # when using magics with decorator @output_can_be_silenced
   2458 # when the last Python token in the expression is a ';'.
   2459 if getattr(fn, magic.MAGIC_OUTPUT_CAN_BE_SILENCED, False):

File /om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.9/site-packages/IPython/core/magics/extension.py:33, in ExtensionMagics.load_ext(self, module_str)
     31 if not module_str:
     32     raise UsageError('Missing module name.')
---> 33 res = self.shell.extension_manager.load_extension(module_str)
     35 if res == 'already loaded':
     36     print(\"The %s extension is already loaded. To reload it, use:\" % module_str)

File /om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.9/site-packages/IPython/core/extensions.py:76, in ExtensionManager.load_extension(self, module_str)
     69 \"\"\"Load an IPython extension by its module name.
     70 
     71 Returns the string \"already loaded\" if the extension is already loaded,
     72 \"no load function\" if the module doesn't have a load_ipython_extension
     73 function, or None if it succeeded.
     74 \"\"\"
     75 try:
---> 76     return self._load_extension(module_str)
     77 except ModuleNotFoundError:
     78     if module_str in BUILTINS_EXTS:

File /om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.9/site-packages/IPython/core/extensions.py:91, in ExtensionManager._load_extension(self, module_str)
     89 with self.shell.builtin_trap:
     90     if module_str not in sys.modules:
---> 91         mod = import_module(module_str)
     92     mod = sys.modules[module_str]
     93     if self._call_load_ipython_extension(mod):

File /om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.9/importlib/__init__.py:127, in import_module(name, package)
    125             break
    126         level += 1
--> 127 return _bootstrap._gcd_import(name[level:], package, level)

File <frozen importlib._bootstrap>:1030, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1007, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:972, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:228, in _call_with_frames_removed(f, *args, **kwds)

File <frozen importlib._bootstrap>:1030, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1007, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:986, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:680, in _load_unlocked(spec)

File <frozen importlib._bootstrap_external>:850, in exec_module(self, module)

File <frozen importlib._bootstrap>:228, in _call_with_frames_removed(f, *args, **kwds)

File /om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.9/site-packages/cudf/__init__.py:19
     16 from rmm.allocators.cupy import rmm_cupy_allocator
     17 from rmm.allocators.numba import RMMNumbaManager
---> 19 from cudf import api, core, datasets, testing
     20 from cudf.api.extensions import (
     21     register_dataframe_accessor,
     22     register_index_accessor,
     23     register_series_accessor,
     24 )
     25 from cudf.api.types import dtype

File /om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.9/site-packages/cudf/datasets.py:7
      4 import pandas as pd
      6 import cudf
----> 7 from cudf._lib.transform import bools_to_mask
      8 from cudf.core.column_accessor import ColumnAccessor
     10 __all__ = [\"timeseries\", \"randomdata\"]

File /om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.9/site-packages/cudf/_lib/__init__.py:4
      1 # Copyright (c) 2020-2023, NVIDIA CORPORATION.
      2 import numpy as np
----> 4 from . import (
      5     avro,
      6     binaryop,
      7     concat,
      8     copying,
      9     csv,
     10     datetime,
     11     expressions,
     12     filling,
     13     groupby,
     14     hash,
     15     interop,
     16     join,
     17     json,
     18     labeling,
     19     merge,
     20     null_mask,
     21     nvtext,
     22     orc,
     23     parquet,
     24     partitioning,
     25     pylibcudf,
     26     quantiles,
     27     reduce,
     28     replace,
     29     reshape,
     30     rolling,
     31     round,
     32     search,
     33     sort,
     34     stream_compaction,
     35     string_casting,
     36     strings,
     37     strings_udf,
     38     text,
     39     timezone,
     40     transpose,
     41     unary,
     42 )
     44 MAX_COLUMN_SIZE = np.iinfo(np.int32).max
     45 MAX_COLUMN_SIZE_STR = \"INT32_MAX\"

ImportError: /om2/user/qsimeon/miniconda3/envs/worm-graph/lib/python3.9/site-packages/cudf/_lib/../../../../libcudf.so: undefined symbol: _ZN5arrow2fs17FileSystemFromUriERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPS6_"
}
```

**Comment by bdice** [comment]
You probably have a conflict with arrow from the earlier pip installation. You’ll need to uninstall any pyarrow packages from pip and reinstall pyarrow from conda.

**Comment by qsimeon** [comment]
Uninstalled with pip:
```
(worm-graph) qsimeon@node102 /om2/user/qsimeon/worm-graph$ pip uninstall pyarrow

Found existing installation: pyarrow 12.0.1
Uninstalling pyarrow-12.0.1:
  Would remove:
    /net/vast-storage/scratch/vast/yanglab/qsimeon/miniconda3/envs/worm-graph/lib/python3.9/site-packages/pyarrow
    /net/vast-storage/scratch/vast/yanglab/qsimeon/miniconda3/envs/worm-graph/lib/python3.9/site-packages/pyarrow-12.0.1-py3.9.egg-info
Proceed (Y/n)? y
  Successfully uninstalled pyarrow-12.0.1
WARNING: Failed to remove contents in a temporary directory '/net/vast-storage/scratch/vast/yanglab/qsimeon/miniconda3/envs/worm-graph/lib/python3.9/site-packages/~yarrow'.
You can safely remove it manually.
```

Reinstalled with conda:
```
(worm-graph) qsimeon@node102 /om2/user/qsimeon/worm-graph$ conda install pyarrow

Channels:
 - conda-forge
 - defaults
 - rapidsai
 - nvidia
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done
...                                                                                                                                                                                                                                 
Preparing transaction: done                                                                                                                                                                                                                                                  
Verifying transaction: done                                                                                                                                                                                                                                                  
Executing transaction: done                                                                                                                                                                                                                                                  
```

Now it works!
```
import cudf.pandas
cudf.pandas.install()
import pandas as pd
pd
```
<module 'pandas' (ModuleAccelerator(fast=cudf, slow=pandas))>

THANKS
