### ISSUE TITLE
cudf can't detect my GPU: cudf.numba.cuda.cudadrv.driver.CudaAPIError: [500] Call to cuInit results in CUDA_ERROR_NOT_FOUND

### ISSUE THREAD

**Issue by BILL-SUN521** [rapidsai/cudf#15925]
**Describe the bug**
I recently encountered almost the same issue in [https://github.com/rapidsai/cudf/issues/8948](https://github.com/rapidsai/cudf/issues/8948) :I have a GPU on my machine and am trying to **build a docker image within WSL2**. 

**Steps/Code to reproduce bug**
Following the suggestions from [official website](https://docs.rapids.ai/install#wsl2-docker). After I generate and run the RAPIDS docker command:
```
docker run --gpus all --pull always --rm -it \
    --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 \
    -p 8888:8888 -p 8787:8787 -p 8786:8786 \
    nvcr.io/nvidia/rapidsai/notebooks:24.04-cuda12.2-py3.11
```
Then I start jupyter notebook and do import cudf which throws the following warning:
```
/opt/conda/lib/python3.11/site-packages/cudf/utils/_ptxcompiler.py:61: UserWarning: Error getting driver and runtime versions:

stdout:



stderr:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py", line 254, in ensure_initialized
    self.cuInit(0)
  File "/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py", line 327, in safe_cuda_api_call
    self._check_ctypes_error(fname, retcode)
  File "/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py", line 395, in _check_ctypes_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [500] Call to cuInit results in CUDA_ERROR_NOT_FOUND

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py", line 292, in __getattr__
    self.ensure_initialized()
  File "/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py", line 258, in ensure_initialized
    raise CudaSupportError(f"Error at driver init: {description}")
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: Call to cuInit results in CUDA_ERROR_NOT_FOUND (500)


Not patching Numba
  warnings.warn(msg, UserWarning)
/opt/conda/lib/python3.11/site-packages/cudf/utils/gpu_utils.py:149: UserWarning: No NVIDIA GPU detected
  warnings.warn("No NVIDIA GPU detected")
```

**Environment overview (please complete the following information)**
 - Environment location: Winth in WSL2 : Docker

**Environment details**
```
[: unexpected operator
     Not inside a git repository
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=22.04
     DISTRIB_CODENAME=jammy
     DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
     PRETTY_NAME="Ubuntu 22.04.4 LTS"
     NAME="Ubuntu"
     VERSION_ID="22.04"
     VERSION="22.04.4 LTS (Jammy Jellyfish)"
     VERSION_CODENAME=jammy
     ID=ubuntu
     ID_LIKE=debian
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     UBUNTU_CODENAME=jammy
     Linux 7735df28a3f8 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Wed Jun  5 08:50:12 2024
     +-----------------------------------------------------------------------------------------+
     | NVIDIA-SMI 555.52.01              Driver Version: 555.99         CUDA Version: 12.5     |
     |-----------------------------------------+------------------------+----------------------+
     | GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
     |                                         |                        |               MIG M. |
     |=========================================+========================+======================|
     |   0  NVIDIA GeForce RTX 4070 ...    On  |   00000000:01:00.0  On |                  N/A |
     |  0%   40C    P8             17W /  285W |    2912MiB /  16376MiB |      6%      Default |
     |                                         |                        |                  N/A |
     +-----------------------------------------+------------------------+----------------------+
     
     +-----------------------------------------------------------------------------------------+
     | Processes:                                                                              |
     |  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
     |        ID   ID                                                               Usage      |
     |=========================================================================================|
     |    0   N/A  N/A        40      G   /Xwayland                                   N/A      |
     |    0   N/A  N/A        41      G   /Xwayland                                   N/A      |
     +-----------------------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:                       x86_64
     CPU op-mode(s):                     32-bit, 64-bit
     Address sizes:                      39 bits physical, 48 bits virtual
     Byte Order:                         Little Endian
     CPU(s):                             20
     On-line CPU(s) list:                0-19
     Vendor ID:                          GenuineIntel
     Model name:                         13th Gen Intel(R) Core(TM) i5-13600KF
     CPU family:                         6
     Model:                              183
     Thread(s) per core:                 2
     Core(s) per socket:                 10
     Socket(s):                          1
     Stepping:                           1
     BogoMIPS:                           6988.79
     Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq vmx ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves avx_vnni umip waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b fsrm md_clear serialize flush_l1d arch_capabilities
     Virtualization:                     VT-x
     Hypervisor vendor:                  Microsoft
     Virtualization type:                full
     L1d cache:                          480 KiB (10 instances)
     L1i cache:                          320 KiB (10 instances)
     L2 cache:                           20 MiB (10 instances)
     L3 cache:                           24 MiB (1 instance)
     Vulnerability Gather data sampling: Not affected
     Vulnerability Itlb multihit:        Not affected
     Vulnerability L1tf:                 Not affected
     Vulnerability Mds:                  Not affected
     Vulnerability Meltdown:             Not affected
     Vulnerability Mmio stale data:      Not affected
     Vulnerability Retbleed:             Mitigation; Enhanced IBRS
     Vulnerability Spec rstack overflow: Not affected
     Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
     Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
     Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
     Vulnerability Srbds:                Not affected
     Vulnerability Tsx async abort:      Not affected
     
     ***CMake***
     
     ***g++***
     
     ***nvcc***
     /opt/conda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2023 NVIDIA Corporation
     Built on Tue_Aug_15_22:02:13_PDT_2023
     Cuda compilation tools, release 12.2, V12.2.140
     Build cuda_12.2.r12.2/compiler.33191640_0
     
     ***Python***
     /opt/conda/bin/python
     Python 3.11.9
     
     ***Environment Variables***
     PATH                            : /opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
     LD_LIBRARY_PATH                 : /usr/local/nvidia/lib:/usr/local/nvidia/lib64
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    :
     PYTHON_PATH                     :
     
     ***conda packages***
     conda is /opt/conda/bin/conda
     /opt/conda/bin/conda
     # packages in environment at /opt/conda:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                       2_gnu    conda-forge
     aiofiles                  22.1.0             pyhd8ed1ab_0    conda-forge
     aiohttp                   3.9.5           py311h459d7ec_0    conda-forge
     aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
     aiosqlite                 0.19.0             pyhd8ed1ab_0    conda-forge
     alsa-lib                  1.2.11               hd590300_1    conda-forge
     annotated-types           0.6.0              pyhd8ed1ab_0    conda-forge
     anyio                     4.3.0              pyhd8ed1ab_0    conda-forge
     aom                       3.8.2                h59595ed_0    conda-forge
     appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
     archspec                  0.2.3              pyhd8ed1ab_0    conda-forge
     argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
     argon2-cffi-bindings      21.2.0          py311h459d7ec_4    conda-forge
     arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
     asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
     async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
     attr                      2.5.1                h166bdaf_1    conda-forge
     attrs                     23.2.0             pyh71513ae_0    conda-forge
     aws-c-auth                0.7.17               he0b1f16_2    conda-forge
     aws-c-cal                 0.6.11               heb1d5e4_0    conda-forge
     aws-c-common              0.9.15               hd590300_0    conda-forge
     aws-c-compression         0.2.18               hce8ee76_3    conda-forge
     aws-c-event-stream        0.4.2                h01f5eca_8    conda-forge
     aws-c-http                0.8.1               hdb68c23_10    conda-forge
     aws-c-io                  0.14.7               hbfbeace_6    conda-forge
     aws-c-mqtt                0.10.3               h50844eb_4    conda-forge
     aws-c-s3                  0.5.7                hb7bd14b_1    conda-forge
     aws-c-sdkutils            0.1.15               hce8ee76_3    conda-forge
     aws-checksums             0.1.18               hce8ee76_3    conda-forge
     aws-crt-cpp               0.26.6               hf567797_4    conda-forge
     aws-sdk-cpp               1.11.267             hbf3e495_6    conda-forge
     babel                     2.14.0             pyhd8ed1ab_0    conda-forge
     beautifulsoup4            4.12.3             pyha770c72_0    conda-forge
     bleach                    6.1.0              pyhd8ed1ab_0    conda-forge
     blosc                     1.21.5               h0f2a231_0    conda-forge
     bokeh                     3.4.1              pyhd8ed1ab_0    conda-forge
     boltons                   24.0.0             pyhd8ed1ab_0    conda-forge
     branca                    0.7.2              pyhd8ed1ab_0    conda-forge
     brotli                    1.1.0                hd590300_1    conda-forge
     brotli-bin                1.1.0                hd590300_1    conda-forge
     brotli-python             1.1.0           py311hb755f60_1    conda-forge
     brunsli                   0.1                  h9c3ff4c_0    conda-forge
     bzip2                     1.0.8                hd590300_5    conda-forge
     c-ares                    1.28.1               hd590300_0    conda-forge
     c-blosc2                  2.14.3               hb4ffafa_0    conda-forge
     ca-certificates           2024.2.2             hbcca054_0    conda-forge
     cached-property           1.5.2                hd8ed1ab_1    conda-forge
     cached_property           1.5.2              pyha770c72_1    conda-forge
     cachetools                5.3.3              pyhd8ed1ab_0    conda-forge
     cairo                     1.18.0               h3faef2a_0    conda-forge
     certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
     cffi                      1.16.0          py311hb3a22ac_0    conda-forge
     cfitsio                   4.3.1                hbdc6101_0    conda-forge
     charls                    2.4.2                h59595ed_0    conda-forge
     charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
     click                     8.1.7           unix_pyh707e725_0    conda-forge
     click-plugins             1.1.1                      py_0    conda-forge
     cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
     cloudpickle               3.0.0              pyhd8ed1ab_0    conda-forge
     colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
     colorcet                  3.1.0              pyhd8ed1ab_0    conda-forge
     comm                      0.2.2              pyhd8ed1ab_0    conda-forge
     conda                     24.3.0          py311h38be061_0    conda-forge
     conda-libmamba-solver     24.1.0             pyhd8ed1ab_0    conda-forge
     conda-package-handling    2.2.0              pyh38be061_0    conda-forge
     conda-package-streaming   0.9.0              pyhd8ed1ab_0    conda-forge
     contourpy                 1.2.1           py311h9547e67_0    conda-forge
     coverage                  7.5.0           py311h331c9d8_0    conda-forge
     cucim                     24.04.00        cuda12_py311_240410_ga24abfd_0    rapidsai
     cuda-cccl_linux-64        12.2.140             ha770c72_0    conda-forge
     cuda-crt-dev_linux-64     12.2.140             ha770c72_1    conda-forge
     cuda-crt-tools            12.2.140             ha770c72_1    conda-forge
     cuda-cudart               12.2.140             hd3aeb46_0    conda-forge
     cuda-cudart-dev           12.2.140             hd3aeb46_0    conda-forge
     cuda-cudart-dev_linux-64  12.2.140             h59595ed_0    conda-forge
     cuda-cudart-static        12.2.140             hd3aeb46_0    conda-forge
     cuda-cudart-static_linux-64 12.2.140             h59595ed_0    conda-forge
     cuda-cudart_linux-64      12.2.140             h59595ed_0    conda-forge
     cuda-nvcc-dev_linux-64    12.2.140             ha770c72_1    conda-forge
     cuda-nvcc-impl            12.2.140             hd3aeb46_1    conda-forge
     cuda-nvcc-tools           12.2.140             hd3aeb46_1    conda-forge
     cuda-nvrtc                12.2.140             hd3aeb46_0    conda-forge
     cuda-nvvm-dev_linux-64    12.2.140             ha770c72_1    conda-forge
     cuda-nvvm-impl            12.2.140             h59595ed_1    conda-forge
     cuda-nvvm-tools           12.2.140             h59595ed_1    conda-forge
     cuda-profiler-api         12.2.140             ha770c72_0    conda-forge
     cuda-python               12.4.0          py311h7f239a6_1    conda-forge
     cuda-version              12.2                 he2b69de_3    conda-forge
     cudf                      24.04.01        cuda12_py311_240501_gaf9fd840f2_0    rapidsai
     cudf_kafka                24.04.01        cuda12_py311_240501_gaf9fd840f2_0    rapidsai
     cugraph                   24.04.00        cuda12_py311_240410_g8d8fb74c2_0    rapidsai
     cuml                      24.04.00        cuda12_py311_240410_ge7bc67431_0    rapidsai
     cuproj                    24.04.00        cuda12_py311_240410_g7da37aae_0    rapidsai
     cupy                      13.1.0          py311hf829483_4    conda-forge
     cupy-core                 13.1.0          py311he1e6e68_4    conda-forge
     curl                      8.7.1                hca28451_0    conda-forge
     cuspatial                 24.04.00        cuda12_py311_240410_g7da37aae_0    rapidsai
     custreamz                 24.04.01        cuda12_py311_240501_gaf9fd840f2_0    rapidsai
     cuxfilter                 24.04.01        cuda12_py311_240411_g175a4dc_0    rapidsai
     cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
     cyrus-sasl                2.1.27               h54b06d7_7    conda-forge
     cytoolz                   0.12.3          py311h459d7ec_0    conda-forge
     dask                      2024.1.1           pyhd8ed1ab_0    conda-forge
     dask-core                 2024.1.1           pyhd8ed1ab_0    conda-forge
     dask-cuda                 24.04.00        py311_240410_g7ed6735_0    rapidsai
     dask-cudf                 24.04.01        cuda12_py311_240501_gaf9fd840f2_0    rapidsai
     dask-expr                 0.4.0              pyhd8ed1ab_0    conda-forge
     dask-glm                  0.3.2              pyhd8ed1ab_0    conda-forge
     dask-labextension         6.2.0              pyhd8ed1ab_0    conda-forge
     dask-ml                   2023.3.24          pyhd8ed1ab_1    conda-forge
     dask-sql                  2024.3.0        py311h0365493_0    conda-forge
     datashader                0.16.1             pyhd8ed1ab_0    conda-forge
     dav1d                     1.2.1                hd590300_0    conda-forge
     dbus                      1.13.6               h5008d03_3    conda-forge
     debugpy                   1.8.1           py311hb755f60_0    conda-forge
     decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
     defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
     distributed               2024.1.1           pyhd8ed1ab_0    conda-forge
     distro                    1.9.0              pyhd8ed1ab_0    conda-forge
     dlpack                    0.8                  h59595ed_3    conda-forge
     entrypoints               0.4                pyhd8ed1ab_0    conda-forge
     exceptiongroup            1.2.0              pyhd8ed1ab_2    conda-forge
     execnet                   2.1.1              pyhd8ed1ab_0    conda-forge
     executing                 2.0.1              pyhd8ed1ab_0    conda-forge
     expat                     2.6.2                h59595ed_0    conda-forge
     fastapi                   0.110.3            pyhd8ed1ab_0    conda-forge
     fastrlock                 0.8.2           py311hb755f60_2    conda-forge
     fiona                     1.9.5           py311hf8e0aa6_2    conda-forge
     fmt                       10.2.1               h00ab1b0_0    conda-forge
     folium                    0.16.0             pyhd8ed1ab_0    conda-forge
     font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
     font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
     font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
     font-ttf-ubuntu           0.83                 h77eed37_2    conda-forge
     fontconfig                2.14.2               h14ed4e7_0    conda-forge
     fonts-conda-ecosystem     1                             0    conda-forge
     fonts-conda-forge         1                             0    conda-forge
     fonttools                 4.51.0          py311h459d7ec_0    conda-forge
     fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
     freetype                  2.12.1               h267a509_2    conda-forge
     freexl                    2.0.0                h743c826_0    conda-forge
     frozenlist                1.4.1           py311h459d7ec_0    conda-forge
     fsspec                    2024.3.1           pyhca7485f_0    conda-forge
     gdal                      3.8.1           py311h39b4e0e_3    conda-forge
     geopandas                 0.14.4             pyhd8ed1ab_0    conda-forge
     geopandas-base            0.14.4             pyha770c72_0    conda-forge
     geos                      3.12.1               h59595ed_0    conda-forge
     geotiff                   1.7.1               hf074850_14    conda-forge
     gettext                   0.22.5               h59595ed_2    conda-forge
     gettext-tools             0.22.5               h59595ed_2    conda-forge
     gflags                    2.2.2             he1b5a44_1004    conda-forge
     giflib                    5.2.2                hd590300_0    conda-forge
     glib                      2.78.4               hfc55251_0    conda-forge
     glib-tools                2.78.4               hfc55251_0    conda-forge
     glog                      0.7.0                hed5481d_0    conda-forge
     gmock                     1.14.0               ha770c72_1    conda-forge
     graphite2                 1.3.13            h59595ed_1003    conda-forge
     gst-plugins-base          1.22.9               h8e1006c_0    conda-forge
     gstreamer                 1.22.9               h98fc4e7_0    conda-forge
     gtest                     1.14.0               h00ab1b0_1    conda-forge
     h11                       0.14.0             pyhd8ed1ab_0    conda-forge
     h2                        4.1.0              pyhd8ed1ab_0    conda-forge
     harfbuzz                  8.3.0                h3d44ed6_0    conda-forge
     hdf4                      4.2.15               h2a13503_7    conda-forge
     hdf5                      1.14.3          nompi_h4f84152_100    conda-forge
     holoviews                 1.18.3             pyhd8ed1ab_0    conda-forge
     hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
     httpcore                  1.0.5              pyhd8ed1ab_0    conda-forge
     httpx                     0.27.0             pyhd8ed1ab_0    conda-forge
     hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
     icu                       73.2                 h59595ed_0    conda-forge
     idna                      3.7                pyhd8ed1ab_0    conda-forge
     imagecodecs               2024.1.1        py311hd0e15ba_2    conda-forge
     imagecodecs-lite          2019.12.3       py311h1f0f07a_7    conda-forge
     imageio                   2.34.1             pyh4b66e23_0    conda-forge
     importlib-metadata        7.1.0              pyha770c72_0    conda-forge
     importlib_metadata        7.1.0                hd8ed1ab_0    conda-forge
     importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
     iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
     ipykernel                 6.29.3             pyhd33586a_0    conda-forge
     ipython                   8.22.2             pyh707e725_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     ipywidgets                8.1.2              pyhd8ed1ab_0    conda-forge
     isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
     jbig                      2.1               h7f98852_2003    conda-forge
     jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
     jinja2                    3.1.3              pyhd8ed1ab_0    conda-forge
     joblib                    1.4.0              pyhd8ed1ab_0    conda-forge
     json-c                    0.17                 h7ab15ed_0    conda-forge
     json5                     0.9.25             pyhd8ed1ab_0    conda-forge
     jsonpatch                 1.33               pyhd8ed1ab_0    conda-forge
     jsonpointer               2.4             py311h38be061_3    conda-forge
     jsonschema                4.21.1             pyhd8ed1ab_0    conda-forge
     jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
     jsonschema-with-format-nongpl 4.21.1             pyhd8ed1ab_0    conda-forge
     jupyter                   1.0.0             pyhd8ed1ab_10    conda-forge
     jupyter-lsp               2.2.5              pyhd8ed1ab_0    conda-forge
     jupyter-server-proxy      4.1.2              pyhd8ed1ab_0    conda-forge
     jupyter_client            7.4.9              pyhd8ed1ab_0    conda-forge
     jupyter_console           6.6.3              pyhd8ed1ab_0    conda-forge
     jupyter_core              5.7.2           py311h38be061_0    conda-forge
     jupyter_events            0.10.0             pyhd8ed1ab_0    conda-forge
     jupyter_server            2.14.0             pyhd8ed1ab_0    conda-forge
     jupyter_server_fileid     0.9.2              pyhd8ed1ab_0    conda-forge
     jupyter_server_terminals  0.5.3              pyhd8ed1ab_0    conda-forge
     jupyter_server_ydoc       0.8.0              pyhd8ed1ab_0    conda-forge
     jupyter_ydoc              0.2.4              pyhd8ed1ab_0    conda-forge
     jupyterlab                3.6.7              pyhd8ed1ab_0    conda-forge
     jupyterlab-nvdashboard    0.9.0                    pypi_0    pypi
     jupyterlab_pygments       0.3.0              pyhd8ed1ab_0    conda-forge
     jupyterlab_server         2.27.1             pyhd8ed1ab_0    conda-forge
     jupyterlab_widgets        3.0.10             pyhd8ed1ab_0    conda-forge
     jxrlib                    1.1                  hd590300_3    conda-forge
     kealib                    1.5.3                h2f55d51_0    conda-forge
     keyutils                  1.6.1                h166bdaf_0    conda-forge
     kiwisolver                1.4.5           py311h9547e67_1    conda-forge
     krb5                      1.21.2               h659d440_0    conda-forge
     lame                      3.100             h166bdaf_1003    conda-forge
     lazy_loader               0.4                pyhd8ed1ab_0    conda-forge
     lcms2                     2.16                 hb7c19ff_0    conda-forge
     ld_impl_linux-64          2.40                 h55db66e_0    conda-forge
     lerc                      4.0.0                h27087fc_0    conda-forge
     libabseil                 20240116.2      cxx17_h59595ed_0    conda-forge
     libaec                    1.1.3                h59595ed_0    conda-forge
     libarchive                3.7.2                h2aa1ff5_1    conda-forge
     libarrow                  14.0.2          h176673d_15_cpu    conda-forge
     libarrow-acero            14.0.2          hac33072_15_cpu    conda-forge
     libarrow-dataset          14.0.2          hac33072_15_cpu    conda-forge
     libarrow-flight           14.0.2          hd42f311_15_cpu    conda-forge
     libarrow-flight-sql       14.0.2          h9241762_15_cpu    conda-forge
     libarrow-gandiva          14.0.2          hd4ab825_15_cpu    conda-forge
     libarrow-substrait        14.0.2          h9241762_15_cpu    conda-forge
     libasprintf               0.22.5               h661eb56_2    conda-forge
     libasprintf-devel         0.22.5               h661eb56_2    conda-forge
     libavif16                 1.0.4                hd9d6309_2    conda-forge
     libblas                   3.9.0           22_linux64_openblas    conda-forge
     libboost-headers          1.84.0               ha770c72_2    conda-forge
     libbrotlicommon           1.1.0                hd590300_1    conda-forge
     libbrotlidec              1.1.0                hd590300_1    conda-forge
     libbrotlienc              1.1.0                hd590300_1    conda-forge
     libcap                    2.69                 h0f662aa_0    conda-forge
     libcblas                  3.9.0           22_linux64_openblas    conda-forge
     libclang                  15.0.7          default_h127d8a8_5    conda-forge
     libclang13                15.0.7          default_h5d6823c_5    conda-forge
     libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
     libcublas                 12.2.5.6             hd3aeb46_0    conda-forge
     libcublas-dev             12.2.5.6             hd3aeb46_0    conda-forge
     libcucim                  24.04.00        cuda12_240410_ga24abfd_0    rapidsai
     libcudf                   24.04.01        cuda12_240501_gaf9fd840f2_0    rapidsai
     libcudf_kafka             24.04.01        cuda12_240501_gaf9fd840f2_0    rapidsai
     libcufft                  11.0.8.103           hd3aeb46_0    conda-forge
     libcufile                 1.7.2.10             hd3aeb46_0    conda-forge
     libcufile-dev             1.7.2.10             hd3aeb46_0    conda-forge
     libcugraph                24.04.00        cuda12_240410_g8d8fb74c2_0    rapidsai
     libcugraph_etl            24.04.00        cuda12_240410_g8d8fb74c2_0    rapidsai
     libcugraphops             24.04.00        cuda12_240410_g021aa305_0    nvidia
     libcuml                   24.04.00        cuda12_240410_ge7bc67431_0    rapidsai
     libcumlprims              24.04.00        cuda12_240410_gfae5daf_0    nvidia
     libcups                   2.3.3                h4637d8d_4    conda-forge
     libcurand                 10.3.3.141           hd3aeb46_0    conda-forge
     libcurand-dev             10.3.3.141           hd3aeb46_0    conda-forge
     libcurl                   8.7.1                hca28451_0    conda-forge
     libcusolver               11.5.2.141           hd3aeb46_0    conda-forge
     libcusolver-dev           11.5.2.141           hd3aeb46_0    conda-forge
     libcusparse               12.1.2.141           hd3aeb46_0    conda-forge
     libcusparse-dev           12.1.2.141           hd3aeb46_0    conda-forge
     libcuspatial              24.04.00        cuda12_240410_g7da37aae_0    rapidsai
     libdeflate                1.19                 hd590300_0    conda-forge
     libedit                   3.1.20191231         he28a2e2_2    conda-forge
     libev                     4.33                 hd590300_2    conda-forge
     libevent                  2.1.12               hf998b51_1    conda-forge
     libexpat                  2.6.2                h59595ed_0    conda-forge
     libffi                    3.4.2                h7f98852_5    conda-forge
     libflac                   1.4.3                h59595ed_0    conda-forge
     libgcc-ng                 13.2.0               hc881cc4_6    conda-forge
     libgcrypt                 1.10.3               hd590300_0    conda-forge
     libgdal                   3.8.1                h4b8bffa_3    conda-forge
     libgettextpo              0.22.5               h59595ed_2    conda-forge
     libgettextpo-devel        0.22.5               h59595ed_2    conda-forge
     libgfortran-ng            13.2.0               h69a702a_6    conda-forge
     libgfortran5              13.2.0               h43f5ff8_6    conda-forge
     libglib                   2.78.4               h783c2da_0    conda-forge
     libgomp                   13.2.0               hc881cc4_6    conda-forge
     libgoogle-cloud           2.22.0               h9be4e54_1    conda-forge
     libgoogle-cloud-storage   2.22.0               hc7a4891_1    conda-forge
     libgpg-error              1.49                 h4f305b6_0    conda-forge
     libgrpc                   1.62.2               h15f2491_0    conda-forge
     libhwy                    1.1.0                h00ab1b0_0    conda-forge
     libiconv                  1.17                 hd590300_2    conda-forge
     libidn2                   2.3.7                hd590300_0    conda-forge
     libjpeg-turbo             3.0.0                hd590300_1    conda-forge
     libjxl                    0.10.2               hcae5a98_0    conda-forge
     libkml                    1.3.0             h01aab08_1018    conda-forge
     libkvikio                 24.04.00        cuda12_240410_gfb767d7_0    rapidsai
     liblapack                 3.9.0           22_linux64_openblas    conda-forge
     libllvm14                 14.0.6               hcd5def8_4    conda-forge
     libllvm15                 15.0.7               hb3ce162_4    conda-forge
     libmamba                  1.5.8                had39da4_0    conda-forge
     libmambapy                1.5.8           py311hf2555c7_0    conda-forge
     libnetcdf                 4.9.2           nompi_h9612171_113    conda-forge
     libnghttp2                1.58.0               h47da74e_1    conda-forge
     libnl                     3.9.0                hd590300_0    conda-forge
     libnsl                    2.0.1                hd590300_0    conda-forge
     libntlm                   1.4               h7f98852_1002    conda-forge
     libnvjitlink              12.2.140             hd3aeb46_0    conda-forge
     libnvjpeg                 12.2.2.4             h59595ed_0    conda-forge
     libogg                    1.3.4                h7f98852_1    conda-forge
     libopenblas               0.3.27          pthreads_h413a1c8_0    conda-forge
     libopus                   1.3.1                h7f98852_1    conda-forge
     libparquet                14.0.2          h6a7eafb_15_cpu    conda-forge
     libpng                    1.6.43               h2797004_0    conda-forge
     libpq                     16.2                 h33b98f1_1    conda-forge
     libprotobuf               4.25.3               h08a7969_0    conda-forge
     libraft                   24.04.00        cuda12_240410_gfa44bcc8_0    rapidsai
     libraft-headers           24.04.00        cuda12_240410_gfa44bcc8_0    rapidsai
     libraft-headers-only      24.04.00        cuda12_240410_gfa44bcc8_0    rapidsai
     librdkafka                1.9.2                ha5a0de0_2    conda-forge
     libre2-11                 2023.09.01           h5a48ba9_2    conda-forge
     librmm                    24.04.00        cuda12_240410_g8f19c9c3_0    rapidsai
     librttopo                 1.1.0               h8917695_15    conda-forge
     libsndfile                1.2.2                hc60ed4a_1    conda-forge
     libsodium                 1.0.18               h36c2ea0_1    conda-forge
     libsolv                   0.7.28               hfc55251_2    conda-forge
     libspatialindex           1.9.3                h9c3ff4c_4    conda-forge
     libspatialite             5.1.0                h72606ae_3    conda-forge
     libsqlite                 3.45.3               h2797004_0    conda-forge
     libssh2                   1.11.0               h0841786_0    conda-forge
     libstdcxx-ng              13.2.0               h95c4c6d_6    conda-forge
     libsystemd0               255                  h3516f8a_1    conda-forge
     libthrift                 0.19.0               hb90f79a_1    conda-forge
     libtiff                   4.6.0                ha9c0a0a_2    conda-forge
     libunistring              0.9.10               h7f98852_0    conda-forge
     libutf8proc               2.8.0                h166bdaf_0    conda-forge
     libuuid                   2.38.1               h0b41bf4_0    conda-forge
     libuv                     1.48.0               hd590300_0    conda-forge
     libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
     libwebp                   1.3.2                h658648e_1    conda-forge
     libwebp-base              1.3.2                hd590300_1    conda-forge
     libwholegraph             24.04.00        cuda12_240410_g55dfc4d_0    rapidsai
     libxcb                    1.15                 h0b41bf4_0    conda-forge
     libxcrypt                 4.4.36               hd590300_1    conda-forge
     libxgboost                2.0.3           rapidsai_hea4bf7d_2    rapidsai
     libxkbcommon              1.7.0                h662e7e4_0    conda-forge
     libxml2                   2.12.6               h232c23b_2    conda-forge
     libzip                    1.10.1               h2629f0a_3    conda-forge
     libzlib                   1.2.13               hd590300_5    conda-forge
     libzopfli                 1.0.3                h9c3ff4c_0    conda-forge
     linkify-it-py             2.0.3              pyhd8ed1ab_0    conda-forge
     llvmlite                  0.42.0          py311ha6695c7_1    conda-forge
     locket                    1.0.0              pyhd8ed1ab_0    conda-forge
     lz4                       4.3.3           py311h38e4bf4_0    conda-forge
     lz4-c                     1.9.4                hcb278e6_0    conda-forge
     lzo                       2.10              hd590300_1001    conda-forge
     mamba                     1.5.8           py311h3072747_0    conda-forge
     mapclassify               2.6.1              pyhd8ed1ab_0    conda-forge
     markdown                  3.6                pyhd8ed1ab_0    conda-forge
     markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
     markupsafe                2.1.5           py311h459d7ec_0    conda-forge
     matplotlib                3.8.4           py311h38be061_0    conda-forge
     matplotlib-base           3.8.4           py311h54ef318_0    conda-forge
     matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
     mdit-py-plugins           0.4.0              pyhd8ed1ab_0    conda-forge
     mdurl                     0.1.2              pyhd8ed1ab_0    conda-forge
     menuinst                  2.0.2           py311h38be061_0    conda-forge
     minizip                   4.0.5                h0ab5242_0    conda-forge
     mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
     mpg123                    1.32.6               h59595ed_0    conda-forge
     msgpack-python            1.0.7           py311h9547e67_0    conda-forge
     multidict                 6.0.5           py311h459d7ec_0    conda-forge
     multipledispatch          0.6.0                      py_0    conda-forge
     munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
     mysql-common              8.0.33               hf1915f5_6    conda-forge
     mysql-libs                8.0.33               hca2cd23_6    conda-forge
     nbclassic                 1.0.0              pyhb4ecaf3_1    conda-forge
     nbclient                  0.10.0             pyhd8ed1ab_0    conda-forge
     nbconvert                 7.16.4               hd8ed1ab_0    conda-forge
     nbconvert-core            7.16.4             pyhd8ed1ab_0    conda-forge
     nbconvert-pandoc          7.16.4               hd8ed1ab_0    conda-forge
     nbformat                  5.10.4             pyhd8ed1ab_0    conda-forge
     nccl                      2.21.5.1             h3a97aeb_0    conda-forge
     ncurses                   6.4.20240210         h59595ed_0    conda-forge
     nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
     networkx                  3.3                pyhd8ed1ab_1    conda-forge
     nodejs                    20.12.2              hb753e55_0    conda-forge
     notebook                  6.5.6              pyha770c72_0    conda-forge
     notebook-shim             0.2.4              pyhd8ed1ab_0    conda-forge
     nspr                      4.35                 h27087fc_0    conda-forge
     nss                       3.98                 h1d7d5a4_0    conda-forge
     numba                     0.59.1          py311h96b013e_0    conda-forge
     numpy                     1.26.4          py311h64a7726_0    conda-forge
     nvcomp                    3.0.6                h10b603f_0    conda-forge
     nvtx                      0.2.10          py311h459d7ec_0    conda-forge
     nx-cugraph                24.04.00                py311_0    rapidsai
     openjpeg                  2.5.2                h488ebb8_0    conda-forge
     openssl                   3.3.0                hd590300_0    conda-forge
     orc                       2.0.0                h1e5e2c1_0    conda-forge
     overrides                 7.7.0              pyhd8ed1ab_0    conda-forge
     packaging                 24.0               pyhd8ed1ab_0    conda-forge
     pandas                    2.2.1           py311h320fe9a_0    conda-forge
     pandoc                    3.1.13               ha770c72_0    conda-forge
     pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
     panel                     1.4.2              pyhd8ed1ab_0    conda-forge
     param                     2.1.0              pyhca7485f_0    conda-forge
     parso                     0.8.4              pyhd8ed1ab_0    conda-forge
     partd                     1.4.1              pyhd8ed1ab_0    conda-forge
     patsy                     0.5.6              pyhd8ed1ab_0    conda-forge
     pcre2                     10.42                hcad00b1_0    conda-forge
     pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
     pickleshare               0.7.5                   py_1003    conda-forge
     pillow                    10.3.0          py311h18e6fac_0    conda-forge
     pip                       24.0               pyhd8ed1ab_0    conda-forge
     pixman                    0.43.2               h59595ed_0    conda-forge
     pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
     platformdirs              4.2.1              pyhd8ed1ab_0    conda-forge
     pluggy                    1.5.0              pyhd8ed1ab_0    conda-forge
     ply                       3.11               pyhd8ed1ab_2    conda-forge
     poppler                   23.12.0              h590f24d_0    conda-forge
     poppler-data              0.4.12               hd8ed1ab_0    conda-forge
     postgresql                16.2                 h82ecc9d_1    conda-forge
     proj                      9.3.0                h1d62c97_2    conda-forge
     prometheus_client         0.20.0             pyhd8ed1ab_0    conda-forge
     prompt-toolkit            3.0.42             pyha770c72_0    conda-forge
     prompt_toolkit            3.0.42               hd8ed1ab_0    conda-forge
     protobuf                  4.25.3          py311h7b78aeb_0    conda-forge
     psutil                    5.9.8           py311h459d7ec_0    conda-forge
     pthread-stubs             0.4               h36c2ea0_1001    conda-forge
     ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
     pulseaudio-client         16.1                 hb77b528_5    conda-forge
     pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
     py-cpuinfo                9.0.0              pyhd8ed1ab_0    conda-forge
     py-xgboost                2.0.3           rapidsai_pyhf96fb25_2    rapidsai
     pyarrow                   14.0.2          py311h78dcc79_15_cpu    conda-forge
     pyarrow-hotfix            0.6                pyhd8ed1ab_0    conda-forge
     pybind11-abi              4                    hd8ed1ab_3    conda-forge
     pycosat                   0.6.6           py311h459d7ec_0    conda-forge
     pycparser                 2.22               pyhd8ed1ab_0    conda-forge
     pyct                      0.5.0              pyhd8ed1ab_0    conda-forge
     pydantic                  2.7.1              pyhd8ed1ab_0    conda-forge
     pydantic-core             2.18.2          py311h5ecf98a_0    conda-forge
     pydeck                    0.8.0              pyhd8ed1ab_0    conda-forge
     pyee                      8.1.0              pyhd8ed1ab_0    conda-forge
     pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
     pylibcugraph              24.04.00        cuda12_py311_240410_g8d8fb74c2_0    rapidsai
     pylibraft                 24.04.00        cuda12_py311_240410_gfa44bcc8_0    rapidsai
     pylibwholegraph           24.04.00        cuda12_py311_240410_g55dfc4d_0    rapidsai
     pynvjitlink               0.2.2           py311hdaa3023_0    rapidsai
     pynvml                    11.4.1             pyhd8ed1ab_0    conda-forge
     pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
     pyppeteer                 1.0.2              pyhd8ed1ab_0    conda-forge
     pyproj                    3.6.1           py311h1facc83_4    conda-forge
     pyqt                      5.15.9          py311hf0fb5b6_5    conda-forge
     pyqt5-sip                 12.12.2         py311hb755f60_5    conda-forge
     pysocks                   1.7.1              pyha2e5f31_6    conda-forge
     pytest                    8.2.0              pyhd8ed1ab_0    conda-forge
     pytest-benchmark          4.0.0              pyhd8ed1ab_0    conda-forge
     pytest-cov                5.0.0              pyhd8ed1ab_0    conda-forge
     pytest-xdist              3.5.0              pyhd8ed1ab_0    conda-forge
     python                    3.11.9          hb806964_0_cpython    conda-forge
     python-confluent-kafka    1.9.2           py311hd4cff14_2    conda-forge
     python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
     python-fastjsonschema     2.19.1             pyhd8ed1ab_0    conda-forge
     python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
     python-louvain            0.16               pyhd8ed1ab_0    conda-forge
     python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
     python_abi                3.11                    4_cp311    conda-forge
     pytz                      2024.1             pyhd8ed1ab_0    conda-forge
     pyviz_comms               2.3.2              pyhd8ed1ab_0    conda-forge
     pywavelets                1.4.1           py311h1f0f07a_1    conda-forge
     pyyaml                    6.0.1           py311h459d7ec_1    conda-forge
     pyzmq                     24.0.1          py311ha4b6469_1    conda-forge
     qt-main                   5.15.8              h5810be5_19    conda-forge
     qtconsole-base            5.5.1              pyha770c72_0    conda-forge
     qtpy                      2.4.1              pyhd8ed1ab_0    conda-forge
     raft-dask                 24.04.00        cuda12_py311_240410_gfa44bcc8_0    rapidsai
     rapids                    24.04.00        cuda12_py311_240411_gb301c96_0    rapidsai
     rapids-dask-dependency    24.04.01                   py_0    rapidsai
     rapids-xgboost            24.04.00        cuda12_py311_240411_gb301c96_0    rapidsai
     rav1e                     0.6.6                he8a937b_2    conda-forge
     rdma-core                 51.0                 hd3aeb46_0    conda-forge
     re2                       2023.09.01           h7f4b329_2    conda-forge
     readline                  8.2                  h8228510_1    conda-forge
     referencing               0.35.0             pyhd8ed1ab_0    conda-forge
     reproc                    14.2.4.post0         hd590300_1    conda-forge
     reproc-cpp                14.2.4.post0         h59595ed_1    conda-forge
     requests                  2.31.0             pyhd8ed1ab_0    conda-forge
     rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
     rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
     rich                      13.7.1             pyhd8ed1ab_0    conda-forge
     rmm                       24.04.00        cuda12_py311_240410_g8f19c9c3_0    rapidsai
     rpds-py                   0.18.0          py311h46250e7_0    conda-forge
     rtree                     1.2.0           py311h3bb2b0f_0    conda-forge
     ruamel.yaml               0.18.6          py311h459d7ec_0    conda-forge
     ruamel.yaml.clib          0.2.8           py311h459d7ec_0    conda-forge
     s2n                       1.4.12               h06160fa_0    conda-forge
     scikit-image              0.22.0          py311h320fe9a_2    conda-forge
     scikit-learn              1.2.0           py311h67c5ca5_0    conda-forge
     scipy                     1.13.0          py311h64a7726_0    conda-forge
     seaborn                   0.13.2               hd8ed1ab_2    conda-forge
     seaborn-base              0.13.2             pyhd8ed1ab_2    conda-forge
     send2trash                1.8.3              pyh0d859eb_0    conda-forge
     setuptools                69.5.1             pyhd8ed1ab_0    conda-forge
     shapely                   2.0.4           py311h2032efe_0    conda-forge
     simpervisor               1.0.0              pyhd8ed1ab_0    conda-forge
     sip                       6.7.12          py311hb755f60_0    conda-forge
     six                       1.16.0             pyh6c4a22f_0    conda-forge
     snappy                    1.1.10               hdb0a2a9_1    conda-forge
     sniffio                   1.3.1              pyhd8ed1ab_0    conda-forge
     sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
     soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
     sparse                    0.15.1             pyhd8ed1ab_1    conda-forge
     spdlog                    1.12.0               hd2e6256_2    conda-forge
     sqlite                    3.45.3               h2c6b66d_0    conda-forge
     stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
     starlette                 0.37.2             pyhd8ed1ab_0    conda-forge
     statsmodels               0.14.1          py311h1f0f07a_0    conda-forge
     streamz                   0.6.4              pyh6c4a22f_0    conda-forge
     svt-av1                   2.0.0                h59595ed_0    conda-forge
     tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
     tblib                     3.0.0              pyhd8ed1ab_0    conda-forge
     terminado                 0.18.1             pyh0d859eb_0    conda-forge
     threadpoolctl             3.5.0              pyhc1e730c_0    conda-forge
     tifffile                  2024.4.18          pyhd8ed1ab_0    conda-forge
     tiledb                    2.18.2               h99f50a1_1    conda-forge
     tinycss2                  1.3.0              pyhd8ed1ab_0    conda-forge
     tk                        8.6.13          noxft_h4845f30_101    conda-forge
     toml                      0.10.2             pyhd8ed1ab_0    conda-forge
     tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
     toolz                     0.12.1             pyhd8ed1ab_0    conda-forge
     tornado                   6.4             py311h459d7ec_0    conda-forge
     tqdm                      4.66.2             pyhd8ed1ab_0    conda-forge
     traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
     treelite                  4.1.2           py311he8f9275_1    conda-forge
     truststore                0.8.0              pyhd8ed1ab_0    conda-forge
     types-python-dateutil     2.9.0.20240316     pyhd8ed1ab_0    conda-forge
     typing-extensions         4.11.0               hd8ed1ab_0    conda-forge
     typing_extensions         4.11.0             pyha770c72_0    conda-forge
     typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
     tzcode                    2024a                h3f72095_0    conda-forge
     tzdata                    2024a                h0c530f3_0    conda-forge
     tzlocal                   5.2             py311h38be061_0    conda-forge
     uc-micro-py               1.0.3              pyhd8ed1ab_0    conda-forge
     ucx                       1.15.0               hda83522_8    conda-forge
     ucx-proc                  1.0.0                       gpu    rapidsai
     ucx-py                    0.37.00         py311_240410_gcb8f84c_0    rapidsai
     uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
     uriparser                 0.9.7                h59595ed_1    conda-forge
     urllib3                   1.26.18            pyhd8ed1ab_0    conda-forge
     uvicorn                   0.29.0          py311h38be061_0    conda-forge
     wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
     webcolors                 1.13               pyhd8ed1ab_0    conda-forge
     webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
     websocket-client          1.8.0              pyhd8ed1ab_0    conda-forge
     websockets                10.4            py311hd4cff14_1    conda-forge
     wget                      1.21.4               hda4d442_0    conda-forge
     wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
     widgetsnbextension        4.0.10             pyhd8ed1ab_0    conda-forge
     xarray                    2024.3.0           pyhd8ed1ab_0    conda-forge
     xcb-util                  0.4.0                hd590300_1    conda-forge
     xcb-util-image            0.4.0                h8ee46fc_1    conda-forge
     xcb-util-keysyms          0.4.0                h8ee46fc_1    conda-forge
     xcb-util-renderutil       0.3.9                hd590300_1    conda-forge
     xcb-util-wm               0.4.1                h8ee46fc_1    conda-forge
     xerces-c                  3.2.5                hac6953d_0    conda-forge
     xgboost                   2.0.3           rapidsai_pyhcb9e655_2    rapidsai
     xkeyboard-config          2.41                 hd590300_0    conda-forge
     xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
     xorg-libice               1.1.1                hd590300_0    conda-forge
     xorg-libsm                1.2.4                h7391055_0    conda-forge
     xorg-libx11               1.8.9                h8ee46fc_0    conda-forge
     xorg-libxau               1.0.11               hd590300_0    conda-forge
     xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
     xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
     xorg-libxrender           0.9.11               hd590300_0    conda-forge
     xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
     xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
     xorg-xf86vidmodeproto     2.3.1             h7f98852_1002    conda-forge
     xorg-xproto               7.0.31            h7f98852_1007    conda-forge
     xyzservices               2024.4.0           pyhd8ed1ab_0    conda-forge
     xz                        5.2.6                h166bdaf_0    conda-forge
     y-py                      0.5.9           py311hfe55011_0    conda-forge
     yaml                      0.2.5                h7f98852_2    conda-forge
     yaml-cpp                  0.8.0                h59595ed_0    conda-forge
     yarl                      1.9.4           py311h459d7ec_0    conda-forge
     ypy-websocket             0.8.2              pyhd8ed1ab_0    conda-forge
     zeromq                    4.3.5                h75354e8_3    conda-forge
     zfp                       1.0.1                h59595ed_0    conda-forge
     zict                      3.0.0              pyhd8ed1ab_0    conda-forge
     zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
     zlib                      1.2.13               hd590300_5    conda-forge
     zlib-ng                   2.0.7                h0b41bf4_0    conda-forge
     zstandard                 0.22.0          py311haa97af0_0    conda-forge
     zstd                      1.5.5                hfc55251_0    conda-forge
```

**Comment by wence-** [comment]
Hmm, weird. Can we try a few things in the docker container please?

First, what does running this python file show?

```python
from cuda import cuda
print(cuda.cuInit(0))
```

And then this one:

```python
import numba.cuda

print(numba.cuda.cudadrv.driver.locate_driver_and_loader())

print(numba.cuda.cudadrv.driver.driver.cuInit(0))
```

Can you also compile and run this C++ program:

```c++
// Suppose it is named init.cpp
#include <cuda.h>
#include <iostream>

int main(void)
{
  auto err = cuInit(0);
  if (err != CUDA_SUCCESS) {
    std::cout << "cuInit unsuccessful: " << err << std::endl;
  } else {
    std::cout << "cuInit successful: " << err << std::endl;
  }
  return 0;
}
```
And show the output
```
$ nvcc -o init init.cpp -lcuda
$ ./init
$ ldd ./init
```

Thanks!

**Comment by bdice** [comment]
Another possibility would be to check that you have `nvidia-container-runtime`. I'm not 100% sure if this is required for WSL or not. See the docs here: https://docs.rapids.ai/install#docker

**Comment by BILL-SUN521** [comment]
> First, what does running this python file show?
> 
> ```python
> from cuda import cuda
> print(cuda.cuInit(0))
> ```

`(<CUresuIt.CUDA_ERROR_NOT_FOUND: 500>,)`

> And then this one:
> 
> ```python
> import numba.cuda
> 
> print(numba.cuda.cudadrv.driver.locate_driver_and_loader())
> 
> print(numba.cuda.cudadrv.driver.driver.cuInit(0))
> ```

`(<class 'ctypes.CDLL'>, ['libcuda.so', 'libcuda.so.1', '/usr/lib/libcuda.so', '/usr/lib/libcuda.so.1', '/usr/lib64/libcuda.so', '/usr/lib64/libcuda.so.1']) `

```
---------------------------------------------------------------------------
CudaAPIError                              Traceback (most recent call last)
File /opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:254, in Driver.ensure_initialized(self)
    [253](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f657069635f616c6d65696461227d.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:253)     _logger.info('init')
--> [254](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f657069635f616c6d65696461227d.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:254)     self.cuInit(0)
    [255](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f657069635f616c6d65696461227d.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:255) except CudaAPIError as e:

File /opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:327, in Driver._ctypes_wrap_fn.<locals>.safe_cuda_api_call(*args)
    [326](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f657069635f616c6d65696461227d.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:326) retcode = libfn(*args)
--> [327](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f657069635f616c6d65696461227d.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:327) self._check_ctypes_error(fname, retcode)

File /opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:395, in Driver._check_ctypes_error(self, fname, retcode)
    [394](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f657069635f616c6d65696461227d.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:394)     self._detect_fork()
--> [395](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f657069635f616c6d65696461227d.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:395) raise CudaAPIError(retcode, msg)

CudaAPIError: [500] Call to cuInit results in CUDA_ERROR_NOT_FOUND

During handling of the above exception, another exception occurred:

CudaSupportError                          Traceback (most recent call last)
Cell In[1], [line 5](vscode-notebook-cell:?execution_count=1&line=5)
      [1](vscode-notebook-cell:?execution_count=1&line=1) import numba.cuda
      [3](vscode-notebook-cell:?execution_count=1&line=3) print(numba.cuda.cudadrv.driver.locate_driver_and_loader())
----> [5](vscode-notebook-cell:?execution_count=1&line=5) print(numba.cuda.cudadrv.driver.driver.cuInit(0))

File /opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:292, in Driver.__getattr__(self, fname)
    [290](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f657069635f616c6d65696461227d.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:290) def __getattr__(self, fname):
    [291](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f657069635f616c6d65696461227d.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:291)     # First request of a driver API function
--> [292](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f657069635f616c6d65696461227d.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:292)     self.ensure_initialized()
    [294](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f657069635f616c6d65696461227d.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:294)     if self.initialization_error is not None:
    [295](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f657069635f616c6d65696461227d.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:295)         raise CudaSupportError("Error at driver init: \n%s:" %
    [296](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f657069635f616c6d65696461227d.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:296)                                self.initialization_error)

File /opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:258, in Driver.ensure_initialized(self)
    [256](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f657069635f616c6d65696461227d.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:256)     description = f"{e.msg} ({e.code})"
    [257](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f657069635f616c6d65696461227d.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:257)     self.initialization_error = description
--> [258](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f657069635f616c6d65696461227d.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:258)     raise CudaSupportError(f"Error at driver init: {description}")
    [259](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f657069635f616c6d65696461227d.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:259) else:
    [260](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f657069635f616c6d65696461227d.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.11/site-packages/numba/cuda/cudadrv/driver.py:260)     self.pid = _getpid()

CudaSupportError: Error at driver init: Call to cuInit results in CUDA_ERROR_NOT_FOUND (500)
```
Speaking of the C++ program, nvcc is unable to find the gcc compiler on the docker's container. (I'm no a developer so I may get difficulties in dubuging in docker.)

**Comment by vyasr** [comment]
@BILL-SUN521 did you have any luck resolving this problem? Unfortunately the reality with a lot of issues like this, especially once you wind up in a situation like:
> Speaking of the C++ program, nvcc is unable to find the gcc compiler on the docker's container.

are very challenging to debug without direct access to the machine for testing. There are too many things that could be wrong with the system configuration.

**Comment by BILL-SUN521** [comment]
> [@BILL-SUN521](https://github.com/BILL-SUN521) did you have any luck resolving this problem? Unfortunately the reality with a lot of issues like this, especially once you wind up in a situation like:
> 
> > Speaking of the C++ program, nvcc is unable to find the gcc compiler on the docker's container.
> 
> are very challenging to debug without direct access to the machine for testing. There are too many things that could be wrong with the system configuration.

As far as I can remember, maybe I finally had to turn to wsl instead of docker to address this kind of problem, and it worked well. Thanks for helping!

**Comment by vyasr** [comment]
Got it thanks, good to hear!
