### ISSUE TITLE
[BUG] Writing 1.5GB dataframe to csv OOMs a 32GB V100

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#6526]
Writing a 1.44GB dataframe to csv appears to cause an out of memory error on a 32GB V100. Tested this in today's nightlies and the nightlies from 2020-10-05 and it happened in both.

```python
import cudf
import cupy as cp
​
# Setup data
cp.random.seed(12)
​
nrows = 10_000_000
ncols = 18
df = cudf.DataFrame({f"x{i}": cp.random.randn(nrows) for i in cp.arange(ncols)})
print(f"Writing a {df.memory_usage(deep=True).sum() / 1e9} GB DataFrame")
​
df.to_csv("large_example_file.csv", index=False)
del df
Writing a 1.44 GB DataFrame
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-1-2252255f9f96> in <module>
     11 print(f"Writing a {df.memory_usage(deep=True).sum() / 1e9} GB DataFrame")
     12 
---> 13 df.to_csv("large_example_file.csv", index=False)
     14 del df

/raid/nicholasb/miniconda3/envs/reading-data-blog/lib/python3.7/site-packages/cudf/core/dataframe.py in to_csv(self, path_or_buf, sep, na_rep, columns, header, index, line_terminator, chunksize)
   6635             index=index,
   6636             line_terminator=line_terminator,
-> 6637             chunksize=chunksize,
   6638         )
   6639 

/raid/nicholasb/miniconda3/envs/reading-data-blog/lib/python3.7/contextlib.py in inner(*args, **kwds)
     72         def inner(*args, **kwds):
     73             with self._recreate_cm():
---> 74                 return func(*args, **kwds)
     75         return inner
     76 

/raid/nicholasb/miniconda3/envs/reading-data-blog/lib/python3.7/site-packages/cudf/io/csv.py in to_csv(df, path_or_buf, sep, na_rep, columns, header, index, line_terminator, chunksize, **kwargs)
    154             header=header,
    155             line_terminator=line_terminator,
--> 156             rows_per_chunk=rows_per_chunk,
    157         )
    158 

cudf/_lib/csv.pyx in cudf._lib.csv.write_csv()

cudf/_lib/csv.pyx in cudf._lib.csv.write_csv()

MemoryError: std::bad_alloc: CUDA error at: ../include/rmm/mr/device/cuda_memory_resource.hpp:68: cudaErrorMemoryAllocation out of memory
```

```
conda list | grep "rapids"
cudf                      0.17.0a201014   cuda_10.2_py37_g66f2790571_83    rapidsai-nightly
dask-cuda                 0.17.0a201013            py37_6    rapidsai-nightly
dask-cudf                 0.17.0a201014   py37_g66f2790571_83    rapidsai-nightly
libcudf                   0.17.0a201014   cuda10.2_g66f2790571_83    rapidsai-nightly
librmm                    0.17.0a201014   cuda10.2_g53d1661_5    rapidsai-nightly
rmm                       0.17.0a201014   cuda_10.2_py37_g53d1661_5    rapidsai-nightly
```

**Comment by davidwendt** [comment]
You may need to set the `chunksize` parameter. 
The following worked for me without error:
```
df.to_csv("large_example_file.csv", index=False, chunksize=5000000)
```

**Comment by beckernick** [comment]
Thanks David.

Is there perhaps an opportunity for us to figure a sane default? I wouldn't have expected to need to explicitly chunk a 1.5GB dataframe on a 32gb card. Curious to get your thoughts on whether that might make sense

**Comment by davidwendt** [comment]
Computing the amount of required temporary memory would be expensive. Also, this is only half the problem. Knowing how much memory is available from the memory manager is not currently supported by all device resource types.

**Comment by rjzamora** [comment]
> EDIT: I now see we have the note in the docstring about setting the chunksize argument. If this could be done automatically under the hood that might be quite cool.

Since this is a row count, a good default also depends on the specific dataframe.

**Comment by beckernick** [comment]
Yep, I see how those could pose problems. I'll close this issue and think a bit more on this topic.

**Comment by harrism** [comment]
Why does this use so much memory?

**Comment by beckernick** [comment]
I'm also curious about how the memory use shoots up
