### ISSUE TITLE
Dask Cudf Typing Error while compute

### ISSUE THREAD

**Issue by smriti93** [rapidsai/cudf#9170]
I keep getting Typing Error when I use apply_rows() for a UDF on dask cudf dataframe. Below is the code and error. Kindly note, since I cannot provide actual data, I have created a random dataframe and running that too gave same error, which makes me think if I am missing something major over here.
**Code**
```
def filter_price(key,col_vendors,col_prices,out):
    for i,(var,col_vendor,col_price) in enumerate(key,col_vendors,col_prices):
        if (var>5) & ((col_vendor==599)|(col_vendor==514)|(col_vendor==591)|(col_vendor==529)) & (pd1.notnull(col_price)):
        #if (col_curr=='USD'):
                out[var]=1
        else:
            if (var<5) & (pd1.notnull(col_price)):
            #if (col_curr=='USD'):
                out[var]=0
            else:
                out[var]=2
				
price_df=pd.DataFrame(columns=['vendor_id','concat_col','market_id','priceAmount'])
price_df['vendor_id']=np.random.randint(1,9,5)
price_df['concat_col']=np.random.randint(1,9,5)
price_df['market_id']=np.random.randint(1,9,5)
price_df['priceAmount']=np.random.randint(1,9,5)
price_cudf=cudf.DataFrame.from_pandas(price_df)
price_dask=dask_cudf.from_cudf(price_cudf,n_partitions=1)
res=price_dask.apply_rows(filter_price,incols={'concat_col':'key','vendor_id':'col_vendors','priceAmount':'col_prices'},
                   outcols={'out':np.int16},kwargs={})
res.compute()

```
**Error**
```
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-34-2d9f7e6c940e> in <module>
----> 1 res.compute()

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/dask/base.py in compute(self, **kwargs)
    282         dask.base.compute
    283         """
--> 284         (result,) = compute(self, traverse=False, **kwargs)
    285         return result
    286

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/dask/base.py in compute(*args, **kwargs)
    564         postcomputes.append(x.__dask_postcompute__())
    565
--> 566     results = schedule(dsk, keys, **kwargs)
    567     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    568

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/distributed/client.py in get(self, dsk, keys, workers, allow_other_workers, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2664                     should_rejoin = False
   2665             try:
-> 2666                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2667             finally:
   2668                 for f in futures.values():

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1973             else:
   1974                 local_worker = None
-> 1975             return self.sync(
   1976                 self._gather,
   1977                 futures,

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    841             return future
    842         else:
--> 843             return sync(
    844                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    845             )

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    351     if error[0]:
    352         typ, exc, tb = error[0]
--> 353         raise exc.with_traceback(tb)
    354     else:
    355         return result[0]

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/distributed/utils.py in f()
    334             if callback_timeout is not None:
    335                 future = asyncio.wait_for(future, callback_timeout)
--> 336             result[0] = yield future
    337         except Exception as exc:
    338             error[0] = sys.exc_info()

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/tornado/gen.py in run(self)
    760
    761                     try:
--> 762                         value = future.result()
    763                     except Exception:
    764                         exc_info = sys.exc_info()

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1838                             exc = CancelledError(key)
   1839                         else:
-> 1840                             raise exception.with_traceback(traceback)
   1841                         raise exc
   1842                     if errors == "skip":

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/dask/optimization.py in __call__()
    961         if not len(args) == len(self.inkeys):
    962             raise ValueError("Expected %d args, got %d" % (len(self.inkeys), len(args)))
--> 963         return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
    964
    965     def __reduce__(self):

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/dask/core.py in get()
    149     for key in toposort(dsk):
    150         task = dsk[key]
--> 151         result = _execute_task(task, cache)
    152         cache[key] = result
    153     result = _execute_task(out, cache)

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/dask/core.py in _execute_task()
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/dask/utils.py in apply()
     32 def apply(func, args, kwargs=None):
     33     if kwargs:
---> 34         return func(*args, **kwargs)
     35     else:
     36         return func(*args)

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/dask/dataframe/core.py in apply_and_enforce()
   5663     func = kwargs.pop("_func")
   5664     meta = kwargs.pop("_meta")
-> 5665     df = func(*args, **kwargs)
   5666     if is_dataframe_like(df) or is_series_like(df) or is_index_like(df):
   5667         if not len(df):

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/dask_cudf/core.py in do_apply_rows()
    128
    129         def do_apply_rows(df, func, incols, outcols, kwargs):
--> 130             return df.apply_rows(
    131                 func, incols, outcols, kwargs, cache_key=cache_key
    132             )

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/cudf/core/dataframe.py in apply_rows()
   4783                     "supported on Series with dtypes `str` and `category`."
   4784                 )
-> 4785         return applyutils.apply_rows(
   4786             self,
   4787             func,

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/cudf/utils/applyutils.py in apply_rows()
     83         func, incols, outcols, kwargs, pessimistic_nulls, cache_key=cache_key
     84     )
---> 85     return applyrows.run(df)
     86
     87

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/cudf/utils/applyutils.py in run()
    168         bound = self.sig.bind(**args)
    169         # Launch kernel
--> 170         self.launch_kernel(df, bound.args, **launch_params)
    171         # Prepare pessimistic nullmask
    172         if self.pessimistic_nulls:

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/cudf/utils/applyutils.py in launch_kernel()
    195
    196     def launch_kernel(self, df, args):
--> 197         self.kernel.forall(len(df))(*args)
    198
    199

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/numba/cuda/compiler.py in __call__()
    359             kernel = self.kernel
    360         else:
--> 361             kernel = self.kernel.specialize(*args)
    362         blockdim = self._compute_thread_per_block(kernel)
    363         griddim = (self.ntasks + blockdim - 1) // blockdim

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/numba/cuda/compiler.py in specialize()
   1019         targetoptions = self.targetoptions
   1020         targetoptions['link'] = self.link
-> 1021         specialization = Dispatcher(self.py_func, [types.void(*argtypes)],
   1022                                     targetoptions)
   1023         self.specializations[cc, argtypes] = specialization

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/numba/cuda/compiler.py in __init__()
    897             if len(sigs) > 1:
    898                 raise TypeError("Only one signature supported at present")
--> 899             self.compile(sigs[0])
    900             self._can_compile = False
    901

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/numba/cuda/compiler.py in compile()
   1091             if not self._can_compile:
   1092                 raise RuntimeError("Compilation disabled")
-> 1093             kernel = _Kernel(self.py_func, argtypes, link=self.link,
   1094                              **self.targetoptions)
   1095             # Inspired by _DispatcherBase.add_overload, but differs slightly

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/numba/core/compiler_lock.py in _acquire_compile_lock()
     33         def _acquire_compile_lock(*args, **kwargs):
     34             with self:
---> 35                 return func(*args, **kwargs)
     36         return _acquire_compile_lock
     37

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/numba/cuda/compiler.py in __init__()
    507         self.extensions = extensions or []
    508
--> 509         cres = compile_cuda(self.py_func, types.void, self.argtypes,
    510                             debug=self.debug,
    511                             inline=inline)

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/numba/core/compiler_lock.py in _acquire_compile_lock()
     33         def _acquire_compile_lock(*args, **kwargs):
     34             with self:
---> 35                 return func(*args, **kwargs)
     36         return _acquire_compile_lock
     37

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/numba/cuda/compiler.py in compile_cuda()
     45         flags.set('forceinline')
     46     # Run compilation pipeline
---> 47     cres = compiler.compile_extra(typingctx=typingctx,
     48                                   targetctx=targetctx,
     49                                   func=pyfunc,

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/numba/core/compiler.py in compile_extra()
    604     pipeline = pipeline_class(typingctx, targetctx, library,
    605                               args, return_type, flags, locals)
--> 606     return pipeline.compile_extra(func)
    607
    608

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/numba/core/compiler.py in compile_extra()
    351         self.state.lifted = ()
    352         self.state.lifted_from = None
--> 353         return self._compile_bytecode()
    354
    355     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/numba/core/compiler.py in _compile_bytecode()
    413         """
    414         assert self.state.func_ir is None
--> 415         return self._compile_core()
    416
    417     def _compile_ir(self):

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/numba/core/compiler.py in _compile_core()
    393                 self.state.status.fail_reason = e
    394                 if is_final_pipeline:
--> 395                     raise e
    396         else:
    397             raise CompilerError("All available pipelines exhausted")

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/numba/core/compiler.py in _compile_core()
    384             res = None
    385             try:
--> 386                 pm.run(self.state)
    387                 if self.state.cr is not None:
    388                     break

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/numba/core/compiler_machinery.py in run()
    337                     (self.pipeline_name, pass_desc)
    338                 patched_exception = self._patch_error(msg, e)
--> 339                 raise patched_exception
    340
    341     def dependency_analysis(self):

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/numba/core/compiler_machinery.py in run()
    328                 pass_inst = _pass_registry.get(pss).pass_inst
    329                 if isinstance(pass_inst, CompilerPass):
--> 330                     self._runPass(idx, pass_inst, state)
    331                 else:
    332                     raise BaseException("Legacy pass in use")

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/numba/core/compiler_lock.py in _acquire_compile_lock()
     33         def _acquire_compile_lock(*args, **kwargs):
     34             with self:
---> 35                 return func(*args, **kwargs)
     36         return _acquire_compile_lock
     37

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/numba/core/compiler_machinery.py in _runPass()
    287             mutated |= check(pss.run_initialization, internal_state)
    288         with SimpleTimer() as pass_time:
--> 289             mutated |= check(pss.run_pass, internal_state)
    290         with SimpleTimer() as finalize_time:
    291             mutated |= check(pss.run_finalizer, internal_state)

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/numba/core/compiler_machinery.py in check()
    260
    261         def check(func, compiler_state):
--> 262             mangled = func(compiler_state)
    263             if mangled not in (True, False):
    264                 msg = ("CompilerPass implementations should return True/False. "

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/numba/core/typed_passes.py in run_pass()
    102                               % (state.func_id.func_name,)):
    103             # Type inference
--> 104             typemap, return_type, calltypes, errs = type_inference_stage(
    105                 state.typingctx,
    106                 state.func_ir,

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/numba/core/typed_passes.py in type_inference_stage()
     80         infer.build_constraint()
     81         # return errors in case of partial typing
---> 82         errs = infer.propagate(raise_errors=raise_errors)
     83         typemap, restype, calltypes = infer.unify(raise_errors=raise_errors)
     84

~/.conda/envs/rapids-0.19/lib/python3.8/site-packages/numba/core/typeinfer.py in propagate()
   1069                                   if isinstance(e, ForceLiteralArg)]
   1070                 if not force_lit_args:
-> 1071                     raise errors[0]
   1072                 else:
   1073                     raise reduce(operator.or_, force_lit_args)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.core.typeinfer.CallConstraint object at 0x7f4a90f71730>.
could not get source code
During: resolving callee type: Function(<numba.cuda.compiler.DeviceFunctionTemplate object at 0x7f4a90f7faf0>)
During: typing of call at <string> (9)

Enable logging at debug level for details.

File "<string>", line 9:
<source missing, REPL/exec in use?>
```

**Comment by quasiben** [comment]
This looks like you are mixing pandas null support within the UDF.  I'd recommend reading through https://docs.rapids.ai/api/cudf/stable/guide-to-udfs.html#Null-Handling-in-UDFs to best handle Nulls

**Comment by gmarkall** [comment]
I was planning to work out a Numba bug report for the `Internal error at <numba.core.typeinfer.CallConstraint object at 0x7f4a90f71730>.` message - however, I can't replicate the error with the provided code. My attempt to replicate it looks like:

```python
import cudf
import dask_cudf
import pandas as pd
import numpy as np


def filter_price(key, col_vendors, col_prices, out):
    for i, (var, col_vendor, col_price) in enumerate(key, col_vendors,
                                                     col_prices):
        if (
            (var > 5)
            & (
                (col_vendor == 599)
                | (col_vendor == 514)
                | (col_vendor == 591)
                | (col_vendor == 529)
            )
            & (pd.notnull(col_price))
        ):
            # if (col_curr=='USD'):
            out[var] = 1
        else:
            if (var < 5) & (pd.notnull(col_price)):
                # if (col_curr=='USD'):
                out[var] = 0
            else:
                out[var] = 2


price_df = pd.DataFrame(columns=["vendor_id", "concat_col", "market_id",
                                 "priceAmount"])
price_df["vendor_id"] = np.random.randint(1, 9, 5)
price_df["concat_col"] = np.random.randint(1, 9, 5)
price_df["market_id"] = np.random.randint(1, 9, 5)
price_df["priceAmount"] = np.random.randint(1, 9, 5)
price_cudf = cudf.DataFrame.from_pandas(price_df)
price_dask = dask_cudf.from_cudf(price_cudf, npartitions=1)
res = price_dask.apply_rows(
    filter_price,
    incols={
        "concat_col": "key",
        "vendor_id": "col_vendors",
        "priceAmount": "col_prices",
    },
    outcols={"out": np.int16},
    kwargs={},
)
res.compute()
```

I had to add imports and rename `pd1` to `pd` to get this to run. I instead get a typing error:

```
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<numba.cuda.compiler.DeviceFunctionTemplate object at 0x7f94ecc62b10>) found for signature:
 
 >>> filter_price <CUDA device function>(array(int64, 1d, A), array(int64, 1d, A), array(int64, 1d, A), array(int16, 1d, A))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'filter_price <CUDA device function>': File: ../../../../../../../../tmp/cudf_9170.py: Line 7.
    With argument(s): '(array(int64, 1d, A), array(int64, 1d, A), array(int64, 1d, A), array(int16, 1d, A))':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in nopython mode pipeline (step: nopython frontend)
   No implementation of function Function(<class 'enumerate'>) found for signature:
    
    >>> enumerate(array(int64, 1d, A), array(int64, 1d, A), array(int64, 1d, A))
    
   There are 2 candidate implementations:
         - Of which 2 did not match due to:
         Overload in function 'Enumerate.generic': File: numba/core/typing/builtins.py: Line 988.
           With argument(s): '(array(int64, 1d, A), array(int64, 1d, A), array(int64, 1d, A))':
          Rejected as the implementation raised a specific error:
            TypeError: Only integers supported as start value in enumerate
     raised from /home/gmarkall/rapidsdev/compose/etc/conda/cuda_11.2/envs/rapids/lib/python3.7/site-packages/numba/core/typing/builtins.py:992
   
   During: resolving callee type: Function(<class 'enumerate'>)
   During: typing of call at cudf_9170.py (9)
   
   
   File "cudf_9170.py", line 9:
   def filter_price(key, col_vendors, col_prices, out):
       <source elided>
       for i, (var, col_vendor, col_price) in enumerate(key, col_vendors,
                                                        col_prices):
```

I expect this is because I'm using a much newer version of Numba and RAPIDS (it looks like you have RAPIDS 0.19, which depends on an earlier version of Numba than the current release, 0.54).

So I think there's no current issue with Numba, but please do update the issue if you still get an `Internal error` message with a later version of RAPIDS / Numba.

**Comment by smriti93** [comment]
> This looks like you are mixing pandas null support within the UDF. I'd recommend reading through https://docs.rapids.ai/api/cudf/stable/guide-to-udfs.html#Null-Handling-in-UDFs to best handle Nulls

Thanks for the suggestion, however the intention was not null handling.

**Comment by smriti93** [comment]
> I was planning to work out a Numba bug report for the `Internal error at <numba.core.typeinfer.CallConstraint object at 0x7f4a90f71730>.` message - however, I can't replicate the error with the provided code. My attempt to replicate it looks like:
> 
> ```python
> import cudf
> import dask_cudf
> import pandas as pd
> import numpy as np
> 
> 
> def filter_price(key, col_vendors, col_prices, out):
>     for i, (var, col_vendor, col_price) in enumerate(key, col_vendors,
>                                                      col_prices):
>         if (
>             (var > 5)
>             & (
>                 (col_vendor == 599)
>                 | (col_vendor == 514)
>                 | (col_vendor == 591)
>                 | (col_vendor == 529)
>             )
>             & (pd.notnull(col_price))
>         ):
>             # if (col_curr=='USD'):
>             out[var] = 1
>         else:
>             if (var < 5) & (pd.notnull(col_price)):
>                 # if (col_curr=='USD'):
>                 out[var] = 0
>             else:
>                 out[var] = 2
> 
> 
> price_df = pd.DataFrame(columns=["vendor_id", "concat_col", "market_id",
>                                  "priceAmount"])
> price_df["vendor_id"] = np.random.randint(1, 9, 5)
> price_df["concat_col"] = np.random.randint(1, 9, 5)
> price_df["market_id"] = np.random.randint(1, 9, 5)
> price_df["priceAmount"] = np.random.randint(1, 9, 5)
> price_cudf = cudf.DataFrame.from_pandas(price_df)
> price_dask = dask_cudf.from_cudf(price_cudf, npartitions=1)
> res = price_dask.apply_rows(
>     filter_price,
>     incols={
>         "concat_col": "key",
>         "vendor_id": "col_vendors",
>         "priceAmount": "col_prices",
>     },
>     outcols={"out": np.int16},
>     kwargs={},
> )
> res.compute()
> ```
> 
> I had to add imports and rename `pd1` to `pd` to get this to run. I instead get a typing error:
> 
> ```
> numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
> No implementation of function Function(<numba.cuda.compiler.DeviceFunctionTemplate object at 0x7f94ecc62b10>) found for signature:
>  
>  >>> filter_price <CUDA device function>(array(int64, 1d, A), array(int64, 1d, A), array(int64, 1d, A), array(int16, 1d, A))
>  
> There are 2 candidate implementations:
>   - Of which 2 did not match due to:
>   Overload in function 'filter_price <CUDA device function>': File: ../../../../../../../../tmp/cudf_9170.py: Line 7.
>     With argument(s): '(array(int64, 1d, A), array(int64, 1d, A), array(int64, 1d, A), array(int16, 1d, A))':
>    Rejected as the implementation raised a specific error:
>      TypingError: Failed in nopython mode pipeline (step: nopython frontend)
>    No implementation of function Function(<class 'enumerate'>) found for signature:
>     
>     >>> enumerate(array(int64, 1d, A), array(int64, 1d, A), array(int64, 1d, A))
>     
>    There are 2 candidate implementations:
>          - Of which 2 did not match due to:
>          Overload in function 'Enumerate.generic': File: numba/core/typing/builtins.py: Line 988.
>            With argument(s): '(array(int64, 1d, A), array(int64, 1d, A), array(int64, 1d, A))':
>           Rejected as the implementation raised a specific error:
>             TypeError: Only integers supported as start value in enumerate
>      raised from /home/gmarkall/rapidsdev/compose/etc/conda/cuda_11.2/envs/rapids/lib/python3.7/site-packages/numba/core/typing/builtins.py:992
>    
>    During: resolving callee type: Function(<class 'enumerate'>)
>    During: typing of call at cudf_9170.py (9)
>    
>    
>    File "cudf_9170.py", line 9:
>    def filter_price(key, col_vendors, col_prices, out):
>        <source elided>
>        for i, (var, col_vendor, col_price) in enumerate(key, col_vendors,
>                                                         col_prices):
> ```
> 
> I expect this is because I'm using a much newer version of Numba and RAPIDS (it looks like you have RAPIDS 0.19, which depends on an earlier version of Numba than the current release, 0.54).
> 
> So I think there's no current issue with Numba, but please do update the issue if you still get an `Internal error` message with a later version of RAPIDS / Numba.

Apologies for the mix up on "pd1" variable. And yes my current Rapids version is 0.19. Let me update both Numba, Rapids and retry. Will update if it still doesn't work.

**Comment by smriti93** [comment]
> I was planning to work out a Numba bug report for the `Internal error at <numba.core.typeinfer.CallConstraint object at 0x7f4a90f71730>.` message - however, I can't replicate the error with the provided code. My attempt to replicate it looks like:
> 
> ```python
> import cudf
> import dask_cudf
> import pandas as pd
> import numpy as np
> 
> 
> def filter_price(key, col_vendors, col_prices, out):
>     for i, (var, col_vendor, col_price) in enumerate(key, col_vendors,
>                                                      col_prices):
>         if (
>             (var > 5)
>             & (
>                 (col_vendor == 599)
>                 | (col_vendor == 514)
>                 | (col_vendor == 591)
>                 | (col_vendor == 529)
>             )
>             & (pd.notnull(col_price))
>         ):
>             # if (col_curr=='USD'):
>             out[var] = 1
>         else:
>             if (var < 5) & (pd.notnull(col_price)):
>                 # if (col_curr=='USD'):
>                 out[var] = 0
>             else:
>                 out[var] = 2
> 
> 
> price_df = pd.DataFrame(columns=["vendor_id", "concat_col", "market_id",
>                                  "priceAmount"])
> price_df["vendor_id"] = np.random.randint(1, 9, 5)
> price_df["concat_col"] = np.random.randint(1, 9, 5)
> price_df["market_id"] = np.random.randint(1, 9, 5)
> price_df["priceAmount"] = np.random.randint(1, 9, 5)
> price_cudf = cudf.DataFrame.from_pandas(price_df)
> price_dask = dask_cudf.from_cudf(price_cudf, npartitions=1)
> res = price_dask.apply_rows(
>     filter_price,
>     incols={
>         "concat_col": "key",
>         "vendor_id": "col_vendors",
>         "priceAmount": "col_prices",
>     },
>     outcols={"out": np.int16},
>     kwargs={},
> )
> res.compute()
> ```
> 
> I had to add imports and rename `pd1` to `pd` to get this to run. I instead get a typing error:
> 
> ```
> numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
> No implementation of function Function(<numba.cuda.compiler.DeviceFunctionTemplate object at 0x7f94ecc62b10>) found for signature:
>  
>  >>> filter_price <CUDA device function>(array(int64, 1d, A), array(int64, 1d, A), array(int64, 1d, A), array(int16, 1d, A))
>  
> There are 2 candidate implementations:
>   - Of which 2 did not match due to:
>   Overload in function 'filter_price <CUDA device function>': File: ../../../../../../../../tmp/cudf_9170.py: Line 7.
>     With argument(s): '(array(int64, 1d, A), array(int64, 1d, A), array(int64, 1d, A), array(int16, 1d, A))':
>    Rejected as the implementation raised a specific error:
>      TypingError: Failed in nopython mode pipeline (step: nopython frontend)
>    No implementation of function Function(<class 'enumerate'>) found for signature:
>     
>     >>> enumerate(array(int64, 1d, A), array(int64, 1d, A), array(int64, 1d, A))
>     
>    There are 2 candidate implementations:
>          - Of which 2 did not match due to:
>          Overload in function 'Enumerate.generic': File: numba/core/typing/builtins.py: Line 988.
>            With argument(s): '(array(int64, 1d, A), array(int64, 1d, A), array(int64, 1d, A))':
>           Rejected as the implementation raised a specific error:
>             TypeError: Only integers supported as start value in enumerate
>      raised from /home/gmarkall/rapidsdev/compose/etc/conda/cuda_11.2/envs/rapids/lib/python3.7/site-packages/numba/core/typing/builtins.py:992
>    
>    During: resolving callee type: Function(<class 'enumerate'>)
>    During: typing of call at cudf_9170.py (9)
>    
>    
>    File "cudf_9170.py", line 9:
>    def filter_price(key, col_vendors, col_prices, out):
>        <source elided>
>        for i, (var, col_vendor, col_price) in enumerate(key, col_vendors,
>                                                         col_prices):
> ```
> 
> I expect this is because I'm using a much newer version of Numba and RAPIDS (it looks like you have RAPIDS 0.19, which depends on an earlier version of Numba than the current release, 0.54).
> 
> So I think there's no current issue with Numba, but please do update the issue if you still get an `Internal error` message with a later version of RAPIDS / Numba.

Hey. I updated rapids and tried again with a simpler function as below.

`def filter_price(key, col_vendors, col_prices, out):
    for i, (var, col_vendor, col_price) in enumerate(key, col_vendors,
                                                     col_prices):
        if (var > 5):
            out[var] = 1
        else:
            if (var < 5):
                out[var] = 0
            else:
                out[var] = 2`

I still get a Typing error like below. I had created an index with unique values and equated it with one of the columns before using the function. If it is not too much, could someone give me a working sample for dataframe which I can modify and debug the source when this issue starts. Right now I'm unable to run any loop code via dask cudf.

`distributed.worker - WARNING - Compute Failed
Function:  subgraph_callable-914057bd-78bc-4841-84bf-6b6e4168
args:      (            vendor_id  market_id  priceAmount  concat_fd
concat_col                                             
85434               6          8            5      85434
115207              3          8            8     115207
176451              2          7            6     176451
424174              3          1            2     424174
1097682             7          5            3    1097682)
kwargs:    {}
Exception: TypingError('Failed in nopython mode pipeline (step: nopython frontend)\nInternal error at <numba.core.typeinfer.CallConstraint object at 0x7fcd2ff05c50>.\n\x1b[1m\x1b[1m\x1b[1mcould not get source code\x1b[0m\n\x1b[0m\x1b[1mDuring: resolving callee type: Function(<numba.cuda.compiler.DeviceFunctionTemplate object at 0x7fcd2fec7050>)\x1b[0m\n\x1b[0m\x1b[1mDuring: typing of call at <string> (9)\n\x1b[0m\nEnable logging at debug level for details.\n\x1b[1m\nFile "<string>", line 9:\x1b[0m\n\x1b[1m<source missing, REPL/exec in use?>\x1b[0m\n')
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
/tmp/ipykernel_7122/1742275039.py in <module>
----> 1 res.compute()
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    284         dask.base.compute
    285         """
--> 286         (result,) = compute(self, traverse=False, **kwargs)
    287         return result
    288
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    566         postcomputes.append(x.__dask_postcompute__())
    567
--> 568     results = schedule(dsk, keys, **kwargs)
    569     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    570
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/distributed/client.py in get(self, dsk, keys, workers, allow_other_workers, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2741                     should_rejoin = False
   2742             try:
-> 2743                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2744             finally:
   2745                 for f in futures.values():
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   2024                 direct=direct,
   2025                 local_worker=local_worker,
-> 2026                 asynchronous=asynchronous,
   2027             )
   2028
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    860         else:
    861             return sync(
--> 862                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    863             )
    864
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    324     if error[0]:
    325         typ, exc, tb = error[0]
--> 326         raise exc.with_traceback(tb)
    327     else:
    328         return result[0]
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/distributed/utils.py in f()
    307             if callback_timeout is not None:
    308                 future = asyncio.wait_for(future, callback_timeout)
--> 309             result[0] = yield future
    310         except Exception:
    311             error[0] = sys.exc_info()
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/tornado/gen.py in run(self)
    760
    761                     try:
--> 762                         value = future.result()
    763                     except Exception:
    764                         exc_info = sys.exc_info()
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1883                             exc = CancelledError(key)
   1884                         else:
-> 1885                             raise exception.with_traceback(traceback)
   1886                         raise exc
   1887                     if errors == "skip":
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/dask/optimization.py in __call__()
    967         if not len(args) == len(self.inkeys):
    968             raise ValueError("Expected %d args, got %d" % (len(self.inkeys), len(args)))
--> 969         return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
    970
    971     def __reduce__(self):
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/dask/core.py in get()
    149     for key in toposort(dsk):
    150         task = dsk[key]
--> 151         result = _execute_task(task, cache)
    152         cache[key] = result
    153     result = _execute_task(out, cache)
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/dask/core.py in _execute_task()
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/dask/utils.py in apply()
     33 def apply(func, args, kwargs=None):
     34     if kwargs:
---> 35         return func(*args, **kwargs)
     36     else:
     37         return func(*args)
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/dask/dataframe/core.py in apply_and_enforce()
   5837     func = kwargs.pop("_func")
   5838     meta = kwargs.pop("_meta")
-> 5839     df = func(*args, **kwargs)
   5840     if is_dataframe_like(df) or is_series_like(df) or is_index_like(df):
   5841         if not len(df):
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/dask_cudf/core.py in do_apply_rows()
    120         def do_apply_rows(df, func, incols, outcols, kwargs):
    121             return df.apply_rows(
--> 122                 func, incols, outcols, kwargs, cache_key=cache_key
    123             )
    124
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/cudf/core/dataframe.py in apply_rows()
   4851             kwargs,
   4852             pessimistic_nulls,
-> 4853             cache_key=cache_key,
   4854         )
   4855
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/cudf/utils/applyutils.py in apply_rows()
     76         func, incols, outcols, kwargs, pessimistic_nulls, cache_key=cache_key
     77     )
---> 78     return applyrows.run(df)
     79
     80
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/cudf/utils/applyutils.py in run()
    161         bound = self.sig.bind(**args)
    162         # Launch kernel
--> 163         self.launch_kernel(df, bound.args, **launch_params)
    164         # Prepare pessimistic nullmask
    165         if self.pessimistic_nulls:
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/cudf/utils/applyutils.py in launch_kernel()
    188
    189     def launch_kernel(self, df, args):
--> 190         self.kernel.forall(len(df))(*args)
    191
    192
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/numba/cuda/compiler.py in __call__()
    359             kernel = self.kernel
    360         else:
--> 361             kernel = self.kernel.specialize(*args)
    362         blockdim = self._compute_thread_per_block(kernel)
    363         griddim = (self.ntasks + blockdim - 1) // blockdim
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/numba/cuda/compiler.py in specialize()
   1020         targetoptions['link'] = self.link
   1021         specialization = Dispatcher(self.py_func, [types.void(*argtypes)],
-> 1022                                     targetoptions)
   1023         self.specializations[cc, argtypes] = specialization
   1024         return specialization
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/numba/cuda/compiler.py in __init__()
    897             if len(sigs) > 1:
    898                 raise TypeError("Only one signature supported at present")
--> 899             self.compile(sigs[0])
    900             self._can_compile = False
    901
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/numba/cuda/compiler.py in compile()
   1092                 raise RuntimeError("Compilation disabled")
   1093             kernel = _Kernel(self.py_func, argtypes, link=self.link,
-> 1094                              **self.targetoptions)
   1095             # Inspired by _DispatcherBase.add_overload, but differs slightly
   1096             # because we're inserting a _Kernel object instead of a compiled
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/numba/core/compiler_lock.py in _acquire_compile_lock()
     33         def _acquire_compile_lock(*args, **kwargs):
     34             with self:
---> 35                 return func(*args, **kwargs)
     36         return _acquire_compile_lock
     37
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/numba/cuda/compiler.py in __init__()
    509         cres = compile_cuda(self.py_func, types.void, self.argtypes,
    510                             debug=self.debug,
--> 511                             inline=inline)
    512         fname = cres.fndesc.llvm_func_name
    513         args = cres.signature.args
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/numba/core/compiler_lock.py in _acquire_compile_lock()
     33         def _acquire_compile_lock(*args, **kwargs):
     34             with self:
---> 35                 return func(*args, **kwargs)
     36         return _acquire_compile_lock
     37
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/numba/cuda/compiler.py in compile_cuda()
     51                                   return_type=return_type,
     52                                   flags=flags,
---> 53                                   locals={})
     54
     55     library = cres.library
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/numba/core/compiler.py in compile_extra()
    604     pipeline = pipeline_class(typingctx, targetctx, library,
    605                               args, return_type, flags, locals)
--> 606     return pipeline.compile_extra(func)
    607
    608
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/numba/core/compiler.py in compile_extra()
    351         self.state.lifted = ()
    352         self.state.lifted_from = None
--> 353         return self._compile_bytecode()
    354
    355     def compile_ir(self, func_ir, lifted=(), lifted_from=None):
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/numba/core/compiler.py in _compile_bytecode()
    413         """
    414         assert self.state.func_ir is None
--> 415         return self._compile_core()
    416
    417     def _compile_ir(self):
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/numba/core/compiler.py in _compile_core()
    393                 self.state.status.fail_reason = e
    394                 if is_final_pipeline:
--> 395                     raise e
    396         else:
    397             raise CompilerError("All available pipelines exhausted")
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/numba/core/compiler.py in _compile_core()
    384             res = None
    385             try:
--> 386                 pm.run(self.state)
    387                 if self.state.cr is not None:
    388                     break
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/numba/core/compiler_machinery.py in run()
    337                     (self.pipeline_name, pass_desc)
    338                 patched_exception = self._patch_error(msg, e)
--> 339                 raise patched_exception
    340
    341     def dependency_analysis(self):
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/numba/core/compiler_machinery.py in run()
    328                 pass_inst = _pass_registry.get(pss).pass_inst
    329                 if isinstance(pass_inst, CompilerPass):
--> 330                     self._runPass(idx, pass_inst, state)
    331                 else:
    332                     raise BaseException("Legacy pass in use")
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/numba/core/compiler_lock.py in _acquire_compile_lock()
     33         def _acquire_compile_lock(*args, **kwargs):
     34             with self:
---> 35                 return func(*args, **kwargs)
     36         return _acquire_compile_lock
     37
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/numba/core/compiler_machinery.py in _runPass()
    287             mutated |= check(pss.run_initialization, internal_state)
    288         with SimpleTimer() as pass_time:
--> 289             mutated |= check(pss.run_pass, internal_state)
    290         with SimpleTimer() as finalize_time:
    291             mutated |= check(pss.run_finalizer, internal_state)
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/numba/core/compiler_machinery.py in check()
    260
    261         def check(func, compiler_state):
--> 262             mangled = func(compiler_state)
    263             if mangled not in (True, False):
    264                 msg = ("CompilerPass implementations should return True/False. "
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/numba/core/typed_passes.py in run_pass()
    108                 state.return_type,
    109                 state.locals,
--> 110                 raise_errors=self._raise_errors)
    111             state.typemap = typemap
    112             # save errors in case of partial typing
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/numba/core/typed_passes.py in type_inference_stage()
     80         infer.build_constraint()
     81         # return errors in case of partial typing
---> 82         errs = infer.propagate(raise_errors=raise_errors)
     83         typemap, restype, calltypes = infer.unify(raise_errors=raise_errors)
     84
~/.conda/envs/rapids-21.08/lib/python3.7/site-packages/numba/core/typeinfer.py in propagate()
   1069                                   if isinstance(e, ForceLiteralArg)]
   1070                 if not force_lit_args:
-> 1071                     raise errors[0]
   1072                 else:
   1073                     raise reduce(operator.or_, force_lit_args)
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.core.typeinfer.CallConstraint object at 0x7fcd2ff05c50>.
could not get source code
During: resolving callee type: Function(<numba.cuda.compiler.DeviceFunctionTemplate object at 0x7fcd2fec7050>)
During: typing of call at <string> (9)
Enable logging at debug level for details.
File "<string>", line 9:
<source missing, REPL/exec in use?>`

**Comment by dustinvanstee** [comment]
I ran the above code using the latest NGC on ubuntu container [nvcr.io/nvidia/rapidsai/rapidsai:21.08-cuda11.2-runtime-ubuntu18.04] .

I wasnt able to reproduce the error above, and in fact was able to get a valid output after a small code refactor.  Posting here for reference .. (note the difference between filter_price and filter_price_dv which uses the enumerate(zip( syntax as shown in the [docs](https://docs.rapids.ai/api/cudf/stable/guide-to-udfs.html ). 
```

import cudf
import dask_cudf
import pandas as pd
import numpy as np


def filter_price(key, col_vendors, col_prices, out):
    for var in key:
        if (var > 5):
            out[var] = 1
        else:
            if (var < 5):
                out[var] = 0
            else:
                out[var] = 2

def filter_price_dv(key, col_vendors, col_prices, out):
    for i, (k,v,p) in enumerate(zip(key,col_vendors,col_prices)):
        if (k > 5):
            out[i] = 1
        else:
            if (k < 5):
                out[i] = 0
            else:
                out[i] = 2

price_df = pd.DataFrame(columns=["vendor_id", "concat_col", "market_id",
                                 "priceAmount"])
price_df["vendor_id"] = np.random.randint(1, 9, 15)
price_df["concat_col"] = np.random.randint(1, 9, 15)
price_df["market_id"] = np.random.randint(1, 9, 15)
price_df["priceAmount"] = np.random.randint(1, 9, 15)
price_cudf = cudf.DataFrame.from_pandas(price_df)
print(price_cudf.describe())
price_dask = dask_cudf.from_cudf(price_cudf, npartitions=1)

res = price_dask.apply_rows(
    filter_price_dv,
    incols={
        "concat_col": "key",
        "vendor_id": "col_vendors",
        "priceAmount": "col_prices",
    },
    outcols={"out": np.int16},
    kwargs={},
)
a=res.compute()
print(res)
print(a)
```

Output 
`    vendor_id  concat_col  market_id  priceAmount  out
0           7           3          7            3    0
1           8           7          7            6    1
2           3           1          5            5    0
3           5           6          3            5    1
4           3           5          3            2    2
5           8           8          2            8    1
6           8           7          5            4    1
7           4           1          6            2    0
8           3           5          7            1    2
9           3           6          7            6    1
10          3           5          6            3    2
11          7           1          8            5    0
12          6           7          3            1    1
13          6           4          6            8    0
14          3           7          1            6    1`

**Comment by smriti93** [comment]
> I ran the above code using the latest NGC on ubuntu container [nvcr.io/nvidia/rapidsai/rapidsai:21.08-cuda11.2-runtime-ubuntu18.04] .
> 
> I wasnt able to reproduce the error above, and in fact was able to get a valid output after a small code refactor. Posting here for reference .. (note the difference between filter_price and filter_price_dv which uses the enumerate(zip( syntax as shown in the [docs](https://docs.rapids.ai/api/cudf/stable/guide-to-udfs.html).
> 
> ```
> 
> import cudf
> import dask_cudf
> import pandas as pd
> import numpy as np
> 
> 
> def filter_price(key, col_vendors, col_prices, out):
>     for var in key:
>         if (var > 5):
>             out[var] = 1
>         else:
>             if (var < 5):
>                 out[var] = 0
>             else:
>                 out[var] = 2
> 
> def filter_price_dv(key, col_vendors, col_prices, out):
>     for i, (k,v,p) in enumerate(zip(key,col_vendors,col_prices)):
>         if (k > 5):
>             out[i] = 1
>         else:
>             if (k < 5):
>                 out[i] = 0
>             else:
>                 out[i] = 2
> 
> price_df = pd.DataFrame(columns=["vendor_id", "concat_col", "market_id",
>                                  "priceAmount"])
> price_df["vendor_id"] = np.random.randint(1, 9, 15)
> price_df["concat_col"] = np.random.randint(1, 9, 15)
> price_df["market_id"] = np.random.randint(1, 9, 15)
> price_df["priceAmount"] = np.random.randint(1, 9, 15)
> price_cudf = cudf.DataFrame.from_pandas(price_df)
> print(price_cudf.describe())
> price_dask = dask_cudf.from_cudf(price_cudf, npartitions=1)
> 
> res = price_dask.apply_rows(
>     filter_price_dv,
>     incols={
>         "concat_col": "key",
>         "vendor_id": "col_vendors",
>         "priceAmount": "col_prices",
>     },
>     outcols={"out": np.int16},
>     kwargs={},
> )
> a=res.compute()
> print(a)
> ```
> 
> Output
> 
> ```
> vendor_id  concat_col  market_id  priceAmount  out
> 0           7           3          7            3    0
> 1           8           7          7            6    1
> 2           3           1          5            5    0
> 3           5           6          3            5    1
> 4           3           5          3            2    2
> 5           8           8          2            8    1
> 6           8           7          5            4    1
> 7           4           1          6            2    0
> 8           3           5          7            1    2
> 9           3           6          7            6    1
> 10          3           5          6            3    2
> 11          7           1          8            5    0
> 12          6           7          3            1    1
> 13          6           4          6            8    0
> 14          3           7          1            6    1
> ```

Thank you so so much @dustinvanstee . This works. Didn't realize not using passed parameters will result in such an error. Though this works I still need to figure out memory issues since the field on which I want to iterate this over has about a million unique values and always results into CUDA Runtime error and shows memory allocation issues.

That being said, this particular issue has been resolved. However I don't think not utilizing parameters or not using enumerate, zip should give out such errors. Rest is up to the Rapids team to close it as resolved or not. Thanks again to everyone who looked into it.

**Comment by beckernick** [comment]
Glad this is now working!

> However I don't think not utilizing parameters or not using enumerate, zip should give out such errors.

Thanks for the feedback. Providing meaningful errors is important but can be challenging in this kind of situation. We'll evaluate ways we can improve here.

> Though this works I still need to figure out memory issues since the field on which I want to iterate this over has about a million unique values and always results into CUDA Runtime error and shows memory allocation issues.

Are you running into issues on a dataset with one million rows? Or much larger dataset with one million unique values. In the code snippets in this issue, people are calling `res.compute()` to trigger computation. This both triggers computation and collects the results into a separate Client process outside of distributed worker memory. Unless that is explicitly the goal, we generally recommend calling `.persist()`.

**Comment by smriti93** [comment]
> Glad this is now working!
> 
> > However I don't think not utilizing parameters or not using enumerate, zip should give out such errors.
> 
> Thanks for the feedback. Providing meaningful errors is important but can be challenging in this kind of situation. We'll evaluate ways we can improve here.
> 
> > Though this works I still need to figure out memory issues since the field on which I want to iterate this over has about a million unique values and always results into CUDA Runtime error and shows memory allocation issues.
> 
> Are you running into issues on a dataset with one million rows? Or much larger dataset with one million unique values. In the code snippets in this issue, people are calling `res.compute()` to trigger computation. This both triggers computation and collects the results into a separate Client process outside of distributed worker memory. Unless that is explicitly the goal, we generally recommend calling `.persist()`.

The latter option with one million unique values @beckernick. Dataset had more than 2 million rows. So basically the memory error issues I was facing happened because GPU didn't have enough memory at runtime. I kept getting cudaErrorMemoryAllocation out of memory. Once the entire environment was restarted by admin, my code ran fine with the larger dataset as well. Thanks for the suggestion though. Will keep in mind to persist before computing. Hoping I don't run into the same again.

**Comment by beckernick** [comment]
Great, glad to hear it.

I'm going to close this issue as resolved.
